### ISSUE TITLE
Cannot run on Ubuntu bionic: libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by probonopd** [gaphor/gaphor#1023]
### Describe the bug
Was built on a too new system, hence cannot run on Ubuntu bionic

### To Reproduce
1. Run Ubuntu bionic
2. Download the AppImage
3. Try to run it

> [11] Error loading Python lib '/run/firejail/appimage/.appimage-9576/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/firejail/appimage/.appimage-9576/libpython3.9.so.1.0)

### Expected behavior
Works

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: Latest

### Additional information
Please build on an older system, no later than Ubuntu bionic. Thanks!

Reference:
https://github.com/AppImage/appimage.github.io/pull/2752

**Comment by danyeaw** [comment]
Hi @probonopd, I agree that it would be preferred to build on an older version of Ubuntu, but we aren't willing to use a 3-4 year old version of GTK to do that - that's not something we are interested in as open source developers. I think we previously discussed this in https://github.com/gaphor/gaphor/issues/534.

We would be happy to have someone setup an AppImage build using any older distribution with newer dependencies or use something like appimage-builder, but I think this would be considerable work to setup.

**Comment by probonopd** [comment]
Indeed, if you require the latest Gtk then the appimage-builder route may be the best one. Thanks for considering it.

**Comment by amolenaar** [comment]
Should we still consider supporting Ubuntu 18.04 (Bionic)? You may run your server on it, but is anyone really running it as their day-to-day desktop? Ubuntu 20.04 is their new LTS version (our current build target).

**Comment by probonopd** [comment]
For desktop apps, I recommend to always ensure they are running on all still-supported releases of Ubuntu, which includes Bionic at this time. Thanks!

**Comment by danyeaw** [comment]
I tried to use appimage-builder today and ran in to this issue: https://github.com/AppImageCrafters/appimage-builder/issues/165

**Comment by danyeaw** [comment]
Another option I have been investigating is to use PyInstaller to freeze the app in to a single executable and then use staticx to create static executables that don't depend on the system glibc. Alternatively we could also use elf convert library that appimage-builder uses to convert our ELF files.

**Comment by amolenaar** [comment]
@danyeaw Interesting exercise :) Some parts of GTK (main pixbuf modules) are always loaded dynamically, BTW.

**Comment by danyeaw** [comment]
Quick update on this, the previous options I investigated didn't pan out to be good options.

I spent some time trying to compile GTK on Ubuntu 18.04 which also was challenging. I found [BuildStream](https://wiki.gnome.org/Newcomers/BuildSystemComponent) which does make it very straightforward, even on a docker image. This looks very promising.

The build worked successfully, and I can launch gtk3-demo, but the shell it puts me at is specific to the repo that I built from: https://gitlab.gnome.org/GNOME/gnome-build-meta. So in order to get access to our gaphor repo I think I can  create a `gaphor.bst` file. Then I can make GTK and Python dependencies, and it will run the full cached build pipeline in docker and I can build the appimage as the last step.

**Comment by amolenaar** [comment]
It sounds a bit like shooting a mosquito with a canon. BuildStream is linux only I suppose?

**Comment by danyeaw** [comment]
Yes, I think so. I was just thinking about how nice it would be if gvsbuild was built on it though. BuildStream itself is written in Python, so as long as all the upstream projects supported building on Windows, which most of the GTK projects do, but other projects like gettext require heavy patching.

**Comment by danyeaw** [comment]
Another update, BuildStream is a complete sandbox using bubblewrap - which is awesome for the use case of being able to develop for GNOME on any Linux version and not worry about conflicting libraries and being able to quickly make updates and test them.

This doesn't actually help us solve our problem, though. BuildStream builds everything in a separate sandbox, including GLIBC as part of the freedesktop-sdk.

It might be possible to create a full new build stream from scratch using all the versions of every library we need without the freedesktop-sdk, but this would be a lot of work and to your point about the canon. You probably got to this point much faster than I did, I'll try to keep up :sweat_smile:

**Comment by danyeaw** [comment]
I created a draft PR, I successfully have built GTK, gobject-introspection, GtkSourceView, and their dependencies on Ubuntu 18.04.

The next step is that pycairo is failing to build a wheel during the install phase (compilation looks like it is working, which is normally where building the wheel fails). I haven't seen this error before:

```
 running install
  Traceback (most recent call last):
    File "/home/gnome/gaphor/.venv-docker/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/gnome/gaphor/.venv-docker/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/gnome/gaphor/.venv-docker/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 567, in <module>
      main()
    File "setup.py", line 534, in main
      setup(
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
      cmd_obj.ensure_finalized()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/command/install.py", line 45, in finalize_options
      orig.install.finalize_options(self)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 366, in finalize_options
      self.finalize_unix()
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 540, in finalize_unix
      self.select_scheme("posix_prefix")
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 565, in select_scheme
      _select_scheme(self, name)
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 127, in _select_scheme
      vars(ob).update(_remove_set(ob, _scheme_attrs(_resolve_scheme(name))))
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 153, in _scheme_attrs
      return {
    File "/tmp/pip-build-env-0_fpmtic/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 154, in <dictcomp>
      f'install_{key}': scheme[key]
  KeyError: 'headers'
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
```

**Comment by danyeaw** [comment]
The above error ended up being pretty straightforward to fix, I had to tell jhbuild to build pycairo and pygobject as well.

**Comment by danyeaw** [comment]
![Screenshot from 2021-12-30 03-48-45](https://user-images.githubusercontent.com/10014976/147720568-2dc2368b-42fb-40bc-b641-ac1635821b8f.png)

Gaphor running on an AppImage in Ubuntu 18.04.

**Comment by probonopd** [comment]
Excellent. Thank you very, very much!
