### ISSUE TITLE
Errors in Italian translation

### ISSUE THREAD

**Issue by Mek101** [gaphor/gaphor#1076]
### Describe the bug
Save silently fails with the following error on console
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gaphor/ui/actiongroup.py", line 173, in _action_activate
    method()
  File "/app/lib/python3.9/site-packages/gaphor/ui/filemanager.py", line 243, in action_save
    return self.action_save_as()
  File "/app/lib/python3.9/site-packages/gaphor/ui/filemanager.py", line 265, in action_save_as
    self.save(filename)
  File "/app/lib/python3.9/site-packages/gaphor/ui/filemanager.py", line 200, in save
    gettext("Saving model to {filename}").format(filename=filename),
KeyError: 'nome file'
```

### To Reproduce
Click save, enter a random name and give ok. Notice that there isn't any file where there should.

### Expected behavior
Be able to save my work

### OS
- [x] Linux (Flatpak)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.4

**Comment by amolenaar** [comment]
Hi @Mek101. Thank you for reaching out.

I checked, and can reproduce this with the command

```
LANG=it_IT flatpak run org.gaphor.Gaphor
```

It is not something that happens by default or with my locale setting (`nl_NL`).

It happens to be an error in the translation file. the file po/it.po has the following lines:

```
#: ../gaphor/ui/filemanager.py:200
msgid "Saving model to {filename}"
msgstr "Salvataggio del modello in {nome file}"
```

The name in curly brackets should still read `filename`, in order to be replaced by the real file.
