### ISSUE TITLE
Type error in element positioning

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#124]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

```
Traceback (most recent call last):
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/view.py", line 900, in do_event
    return self._tool.handle(event) and True or False
  File "/Users/arjan/Development/gaphor/gaphor/ui/diagramtools.py", line 460, in handle
    super(TransactionalToolChain, self).handle(event)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/tool.py", line 215, in handle
    rt = tool.handle(event)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/tool.py", line 124, in handle
    return self._dispatch(event)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/tool.py", line 120, in _dispatch
    return bool(h(event))
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/tool.py", line 235, in on_motion_notify
    view.hovered_item = Finder(view).get_item_at_point(pos)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/aspect.py", line 31, in get_item_at_point
    return item or self.view.get_item_at_point(pos)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/view.py", line 228, in get_item_at_point
    item_distance = item.point((ix, iy))
  File "/Users/arjan/Development/gaphor/gaphor/diagram/classes/association.py", line 222, in point
    super(AssociationItem, self).point(pos),
  File "/Users/arjan/Development/gaphor/gaphor/diagram/diagramline.py", line 52, in point
    d1 = gaphas.Line.point(self, pos)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/item.py", line 698, in point
    distance, point, segment = self.closest_segment(pos)
  File "/Users/arjan/Development/gaphor/.venv/lib/python3.7/site-packages/gaphas/item.py", line 684, in closest_segment
    return reduce(min, list(zip(distances, pols, list(range(len(distances))))))
TypeError: '<' not supported between instances of 'Position' and 'tuple'
```

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

- Gaphas 1.0.0

**Comment by amolenaar** [comment]
Can't reproduce.
