### ISSUE TITLE
TypeError with Alignment Plugin

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#127]
I'm not sure if this is an issue with Gaphor of MSYS2, but I am not able to run Gaphor currently in Windows.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

Run gaphor after installing the wheel with pip on msys2

### Expected behavior
Gaphor runs

### Minimal reproduction of the problem with instructions
```
<MINGW64> C:\tools\msys64\home\dyeaw\gaphor>gaphor
gaphor.application INFO initializing service service.component_registry
gaphor.application INFO initializing service service.main_window
gaphor.ui.stock INFO Icon dir: C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\ui\pixmaps
gaphor.application INFO initializing service service.action_manager
gaphor.services.actionmanager INFO Loading action provider services
gaphor.application INFO initializing service service.ui_manager
gaphor.application INFO initializing service service.properties
gaphor.application INFO initializing service service.adapter_loader
gaphor.application INFO initializing service service.alignment
Traceback (most recent call last):
  File "C:\tools\msys64\mingw64\lib\python3.7\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\tools\msys64\mingw64\lib\python3.7\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\tools\msys64\mingw64\bin\gaphor.exe\__main__.py", line 9, in <module>
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\__init__.py", line 113, in main
    launch(model)
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\__init__.py", line 43, in launch
    Application.init()
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\application.py", line 54, in init
    self.init_all_services()
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\application.py", line 89, in init_all_services
    self.init_service(next(iter(list(self._uninitialized_services.keys()))))
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\application.py", line 103, in init_service
    srv.init(self)
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\plugins\alignment\__init__.py", line 42, in init
    self.update()
  File "C:\tools\msys64\mingw64\lib\python3.7\site-packages\gaphor\plugins\alignment\__init__.py", line 51, in update
    self.action_group.get_action("align-left").set_sensitive(sensitive)
TypeError: Argument 1 does not allow None as a value
```

### System Information
OS:
- [x] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [X] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
I have reproduced this issue in Linux as well with a Flatpak build:
```
(flatpak run:18939): flatpak-DEBUG: 11:28:23.105: Running '/usr/lib/flatpak/flatpak-bwrap --args 33 gaphor'
gaphor.application INFO initializing service service.component_registry
gaphor.application INFO initializing service service.element_dispatcher
gaphor.application INFO initializing service service.main_window
gaphor.ui.stock INFO Icon dir: /app/lib/python3.7/site-packages/gaphor/ui/pixmaps
gaphor.application INFO initializing service service.action_manager
gaphor.services.actionmanager INFO Loading action provider services
gaphor.application INFO initializing service service.properties
gaphor.application INFO initializing service service.adapter_loader
gaphor.application INFO initializing service service.alignment
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 161, in app_startup
    self.init()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 56, in init
    self.init_all_services()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 91, in init_all_services
    self.init_service(next(iter(list(self._uninitialized_services.keys()))))
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 105, in init_service
    srv.init(self)
  File "/app/lib/python3.7/site-packages/gaphor/plugins/alignment/__init__.py", line 42, in init
    self.update()
  File "/app/lib/python3.7/site-packages/gaphor/plugins/alignment/__init__.py", line 51, in update
    self.action_group.get_action("align-left").set_sensitive(sensitive)
TypeError: Argument 1 does not allow None as a value
```
