### ISSUE TITLE
Gaphor stops at greeter

### ISSUE THREAD

**Issue by gwutz** [gaphor/gaphor#1297]
### Describe the bug
When trying Gaphor 2.8 (flatpak) i can't get past the greeter. I assume it is a translation/gettext problem because i get this in the journal:

```
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]: Traceback (most recent call last):
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/ui/greeter.py", line 163, in _on_template_activated
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     session = self.application.new_session(template=translated_model)
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/application.py", line 93, in new_session
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     return self._new_session(
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/application.py", line 99, in _new_session
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     session = Session(services=services)
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/application.py", line 185, in __init__
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     services_by_name: dict[str, Service] = initialize("gaphor.services", services)
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/entrypoint.py", line 13, in initialize
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     return init_entry_points(load_entry_points(scope, services), **known_services)
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/entrypoint.py", line 29, in load_entry_points
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     cls = ep.load()
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     module = import_module(match.group('module'))
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/plugins/console/consolewindow.py", line 11, in <module>
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     from gaphor.plugins.console.console import GTKInterpreterConsole
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:   File "/app/lib/python3.9/site-packages/gaphor/plugins/console/console.py", line 23, in <module>
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]:     banner = gettext(
Jan 16 09:50:44 fedora gnome-software-service.desktop[14749]: KeyError: 'Version'

```

### OS
- [X] Linux (Fedora Silverblue)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.8

**Comment by danyeaw** [comment]
@gwutz Thanks for reporting the issue. Are you running it the your language set to German or English?

**Comment by gwutz** [comment]
German yes

**Comment by danyeaw** [comment]
@all-contributors please add @gwutz for bug

You were right, it was an issue with the translation. The translation string had replaced `{version}` with `{Version}`, and Version wasn't a valid Python object in the code. I have created a PR, and we can release a bug fix version soon :+1:

**Comment by amolenaar** [comment]
@gwutz A workaround, until the new release is out you can run Gaphor with the default locale from the command line: `LANG=C flatpak run org.gaphor.Gaphor`.
