### ISSUE TITLE
Cannot add segments to line connectors

### ISSUE THREAD

**Issue by greedyj4ck** [gaphor/gaphor#1312]
### Describe the bug
After drawing any linear connection, I cannot add segments to change the route.

### To Reproduce
1. Open new diagram
2. Add line, association, generalization or any other line based object
3. Activate object and try to add new segment by clicking on breaking point in the middle.

### Expected behavior
New segment of a line should appear.

### Screenshots

![gaphor-bug](https://user-images.githubusercontent.com/33233389/150515227-b08d5cee-eef6-48b4-8eba-b9da0c15852c.gif)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows 10.0.19044 N/A Build 19044

### Version
Version of Gaphor: 2.8.1 (portable)

**Comment by danyeaw** [comment]
Thanks @greedyj4ck for the issue report, I can reproduce this issue in Windows as well.

@all-contributors please add @greedyj4ck for bug

**Comment by danyeaw** [comment]
@amolenaar could you please take a look at this one or guide me to where the issue might be?

**Comment by amolenaar** [comment]
@danyeaw @greedyj4ck I'll have a look. First check if it *does* work in Gaphas. If it does it's probably something with EventControllers so we need to check those in `gaphor.diagram.tools`.

**Comment by amolenaar** [comment]
It's raising an exception when I try to create a new segment:

```
Traceback (most recent call last):
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/tool/itemtool.py", line 81, in on_drag_begin
    handle = maybe_split_segment(view, item, pos)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/tool/itemtool.py", line 216, in maybe_split_segment
    return segment.split(cpos)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/segment.py", line 30, in split
    handles, ports = self.split_segment(segment)
  File "/home/arjan/Development/gaphor/gaphor/diagram/tools/segment.py", line 12, in split_segment
    line.handle(LineSplitSegmentEvent(line, segment, count))
  File "/home/arjan/Development/gaphor/gaphor/core/modeling/element.py", line 141, in handle
    model.handle(event)
  File "/home/arjan/Development/gaphor/gaphor/core/modeling/elementfactory.py", line 223, in handle
    self.event_manager.handle(event)
  File "/home/arjan/Development/gaphor/gaphor/core/eventmanager.py", line 55, in handle
    self._events.handle(e)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/generic/event.py", line 63, in handle
    handler(event)
  File "/home/arjan/Development/gaphor/gaphor/services/undomanager.py", line 315, in undo_reversible_event
    self.add_undo_action(
  File "/home/arjan/Development/gaphor/gaphor/services/undomanager.py", line 153, in add_undo_action
    raise NotInTransactionException("Updating state outside of a transaction.")
gaphor.services.undomanager.NotInTransactionException: Updating state outside of a transaction.
```
