### ISSUE TITLE
Cannot launch Gaphor

### ISSUE THREAD

**Issue by lukman83** [gaphor/gaphor#1323]
### Describe the bug
Gaphor failed to execute on python virtualenv

### To Reproduce
1. activate virtualenv
2. Install Gaphor and it's dependency pkgconfig, gaphas, pycairo etc
3. type gaphor
Traceback (most recent call last):
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/ui/__init__.py", line 121, in app_activate
    application.new_session()
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/application.py", line 86, in new_session
    return self._new_session(services=services)
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/application.py", line 103, in _new_session
    session = Session(services=services)
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/application.py", line 189, in __init__
    services_by_name: Dict[str, Service] = initialize("gaphor.services", services)
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/entrypoint.py", line 13, in initialize
    return init_entrypoints(load_entrypoints(scope, services), **known_services)
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/entrypoint.py", line 20, in load_entrypoints
    cls = ep.load()
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/home/lukman/python3.8_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/plugins/diagramexport/__init__.py", line 13, in <module>
    from gaphor.diagram.painter import ItemPainter
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/diagram/painter.py", line 16, in <module>
    from gaphor.diagram.selection import Selection
  File "/usr/home/lukman/python3.8_env/lib/python3.8/site-packages/gaphor/diagram/selection.py", line 4, in <module>
    from gaphas.view.selection import Selection as _Selection
ModuleNotFoundError: No module named 'gaphas.view.selection'

### Expected behavior
when we type gaphor the app will launched

### OS
- [ ] FreeBSD 13.0-Stable

### Version
Version of Gaphor: 2.8.1

**Comment by amolenaar** [comment]
Hi @lukman83,

Did you use Poetry (`poetry install`?) In that case you do not have to create a venv yourself and the right (pinned) versions of Gaphor's dependencies are installed.

@all-contributors add @lukman83 for bug.

**Comment by lukman83** [comment]
@amolenaar, i do not install poetry because  i just want to use it not for development, i prefer use virtualenv than pyenv, i already success to install gaphor via PIP (all dependency already satisfied via pip), but failed when i launched it.

**Comment by amolenaar** [comment]
It looks like an older version of Gaphas has been installed. You should have the latest version (3.5.0) installed, with Gaphor >=2.8.0.

I did the following, and all installed and ran (on linux):
```
$ python -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip install gaphor
(.venv) $ gaphor
```
Does this work with you? Else can you provide the commands you perform?

**Comment by lukman83** [comment]
(python3.8_env) ~ » pip install gaphas      
Requirement already satisfied: gaphas in ./python3.8_env/lib/python3.8/site-packages (3.5.0)
Requirement already satisfied: pycairo<2.0.0,>=1.20.0 in ./python3.8_env/lib/python3.8/site-packages (from gaphas) (1.20.1)
Requirement already satisfied: PyGObject<4.0.0,>=3.38.0 in ./python3.8_env/lib/python3.8/site-packages (from gaphas) (3.42.0)
(python3.8_env) ~ » pip install gaphor
Requirement already satisfied: gaphor in ./python3.8_env/lib/python3.8/site-packages (2.5.1)
Requirement already satisfied: importlib_metadata<5.0,>=1.4 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (4.10.1)
Requirement already satisfied: tinycss2<2.0.0,>=1.0.2 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (1.1.1)
Requirement already satisfied: generic<2.0.0,>=1.0.0 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (1.0.1)
Requirement already satisfied: typing_extensions<4.0.0,>=3.7.4 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (3.10.0.2)
Requirement already satisfied: pycairo<2.0,>=1.18 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (1.20.1)
Requirement already satisfied: gaphas<4.0.0,>=3.1.0 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (3.5.0)
Requirement already satisfied: PyGObject<4.0,>=3.30 in ./python3.8_env/lib/python3.8/site-packages (from gaphor) (3.42.0)
Requirement already satisfied: zipp>=0.5 in ./python3.8_env/lib/python3.8/site-packages (from importlib_metadata<5.0,>=1.4->gaphor) (3.7.0)
Requirement already satisfied: webencodings>=0.4 in ./python3.8_env/lib/python3.8/site-packages (from tinycss2<2.0.0,>=1.0.2->gaphor) (0.5.1)

Probably because i use freebsd maybe there are some missing dependency, ok i will use gaphor on my voidlinux, thanks for your response

**Comment by amolenaar** [comment]
It's installing a quite old version of gaphor, when you install Gaphas :/. Gaphor is used by Gaphas, but only for documentation.

If you `pip install gaphor==2.8.1` (not gaph*as*) you should get the latest versions of everything, even on FreeBSD.

**Comment by danyeaw** [comment]
This is an issue with your environment, come chat on Gitter if you need help resolving it.
