### ISSUE TITLE
Flatpak Packages are Not Building on FlatHub

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#135]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Although I can successfully build flatpak packages locally, the builds are failing on FlatHub infrastructure.

### Expected behavior
FlatHub based builds working.

### Minimal reproduction of the problem with instructions
Push the current manifest to https://github.com/flathub/org.gaphor.Gaphor/pull/2 gives the following traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
```
Troubleshooting this is challenging without access to the BuildBot infrastructure. I will submit an issue to the FlatHub team, and update the README to not use Flatpak in Linux until the issue is resolved.

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
Flatpak issues have been resolved :+1:
A test version can be installed with `flatpak install --user https://dl.flathub.org/build-repo/2301/org.gaphor.Gaphor.flatpakref`.
I will keep this issue open until we release version 1.0.1 of Gaphor, maybe once #139 is merged?
