### ISSUE TITLE
Flatpak dosn't run. pycairo dependecy 

### ISSUE THREAD

**Issue by ezickler** [gaphor/gaphor#136]
### I'm submitting a...
- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
flatpak package does not start up. Seams to be a dependency problem with a wrong pycairo version.
```
flatpak run org.gaphor.Gaphor          
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pycairo 1.16.3 (/usr/lib/python3.7/site-packages), Requirement.parse('pycairo>=1.17.0'), {'gaphor'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/gaphor", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycairo>=1.17.0' distribution was not found and is required by gaphor
```

### Expected behavior
open graphor

### System Information
OS:
- [X] Linux Fedora 30
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
@ezickler Thanks for the issue report :heart:. I am aware of the issue and I have actually fixed this error, but now we have run in to another build error on the FlatHub infrastructure. I am working with the FlatHub team to try to resolve it as soon as possible. There is also a tar.gz release available to download as well in the Releases section as a short term workaround.

This issue is closed by #135.

**Comment by danyeaw** [comment]
@all-contributors please add @ezickler for bug

**Comment by danyeaw** [comment]
@all-contributors please add @ezickler for bug
