### ISSUE TITLE
UI Manager / Action Manager is Causing Gaphor Load Errors

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#137]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Run gaphor:
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/services/actionmanager.py", line 75, in register_action_provider
    action_provider.__ui_merge_id
AttributeError: 'MainWindow' object has no attribute '_ActionManager__ui_merge_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 125, in get_service
    return self.component_registry.get_service(name)
  File "/home/dan/Projects/gaphor/gaphor/services/componentregistry.py", line 60, in get_service
    return self.get_utility(IService, name)
  File "/home/dan/Projects/gaphor/gaphor/services/componentregistry.py", line 82, in get_utility
    return self._components.getUtility(provided, name)
  File "/home/dan/.virtualenvs/gaphor/lib/python3.7/site-packages/zope/interface/registry.py", line 286, in getUtility
    raise ComponentLookupError(provided, name)
zope.interface.interfaces.ComponentLookupError: (<InterfaceClass gaphor.interfaces.IService>, 'ui_manager')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 100, in init_service
    srv = self._uninitialized_services.pop(name)
KeyError: 'ui_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 161, in app_startup
    self.init()
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 56, in init
    self.init_all_services()
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 89, in init_all_services
    self.init_service(name)
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 105, in init_service
    srv.init(self)
  File "/home/dan/Projects/gaphor/gaphor/ui/mainwindow.py", line 120, in init
    self.init_action_group()
  File "/home/dan/Projects/gaphor/gaphor/ui/mainwindow.py", line 171, in init_action_group
    self.action_manager.register_action_provider(self)
  File "/home/dan/Projects/gaphor/gaphor/services/actionmanager.py", line 78, in register_action_provider
    self.ui_manager.insert_action_group(action_provider.action_group, -1)
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 224, in __get__
    return Application.get_service(self._name)
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 127, in get_service
    return self.init_service(name)
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 102, in init_service
    raise component.ComponentLookupError(IService, name)
zope.interface.interfaces.ComponentLookupError: (<InterfaceClass gaphor.interfaces.IService>, 'ui_manager')
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/application.py", line 125, in get_service
    return self.component_registry.get_service(name)
  File "/home/dan/Projects/gaphor/gaphor/services/componentregistry.py", line 60, in get_service
    return self.get_utility(IService, name)
  File "/home/dan/Projects/gaphor/gaphor/services/componentregistry.py", line 82, in get_utility
    return self._components.getUtility(provided, name)
  File "/home/dan/.virtualenvs/gaphor/lib/python3.7/site-packages/zope/interface/registry.py", line 286, in getUtility
    raise ComponentLookupError(provided, name)
zope.interface.interfaces.ComponentLookupError: (<InterfaceClass gaphor.interfaces.IService>, 'main_window')
```

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
Closed by #133

**Comment by amolenaar** [comment]
You had to do a `poetry install`, right?

**Comment by danyeaw** [comment]
@amolenaar it actually started working immediately after I merged the 2nd PR.
