### ISSUE TITLE
Flatpak doesn't run with Wayland

### ISSUE THREAD

**Issue by tronta** [gaphor/gaphor#147]
I get a different error when I try to run the flatpak.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
`Gdk-Message: 07:40:00.940: Unable to load sizing from the cursor theme
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 161, in app_startup
    self.init()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 55, in init
    self.load_services(services)
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 79, in load_services
    cls = ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/lib/python3.7/site-packages/gaphor/ui/mainwindow.py", line 31, in <module>
    from gaphor.ui.diagrampage import DiagramPage
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagrampage.py", line 28, in <module>
    from gaphor.ui.diagramtoolbox import DiagramToolbox
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagramtoolbox.py", line 16, in <module>
    from gaphor.ui.diagramtools import PlacementTool, GroupPlacementTool, DefaultTool
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagramtools.py", line 36, in <module>
    OUT_CURSOR = Gdk.Cursor.new(Gdk.CursorType.SIZING)
TypeError: constructor returned NULL
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 166, in app_activate
    main_window = self.get_service("main_window")
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 122, in get_service
    raise NotInitializedError("First call Application.init() to load services")
gaphor.application.NotInitializedError: First call Application.init() to load services
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 178, in app_shutdown
    self.shutdown()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 130, in shutdown
    for name, srv in self.component_registry.get_utilities(IService):
AttributeError: 'NoneType' object has no attribute `'get_utilities'`

### Expected behavior
No error message

### Minimal reproduction of the problem with instructions
I use Fedora 30.

### System Information
OS:
- [X] Linux (Fedora 30)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by danyeaw** [comment]
@tronta Thanks for the issue report ♥️. The latest Flatpak was released  yesterday (version 1.0.1), is this the version you have installed? I will need to try to reproduce this issue some how since I'm not getting those errors with Ubuntu and the latest version.

**Comment by tronta** [comment]
Thank you for your work. Yes it happens with the latest version 1.0.1.

**Comment by danyeaw** [comment]
I have isolated this issue to running Gaphor with Wayland:
```
Gdk-Message: 20:31:03.704: Unable to load sizing from the cursor theme
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 161, in app_startup
    self.init()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 55, in init
    self.load_services(services)
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 79, in load_services
    cls = ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/lib/python3.7/site-packages/gaphor/ui/mainwindow.py", line 31, in <module>
    from gaphor.ui.diagrampage import DiagramPage
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagrampage.py", line 28, in <module>
    from gaphor.ui.diagramtoolbox import DiagramToolbox
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagramtoolbox.py", line 16, in <module>
    from gaphor.ui.diagramtools import PlacementTool, GroupPlacementTool, DefaultTool
  File "/app/lib/python3.7/site-packages/gaphor/ui/diagramtools.py", line 36, in <module>
    OUT_CURSOR = Gdk.Cursor.new(Gdk.CursorType.SIZING)
TypeError: constructor returned NULL
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 166, in app_activate
    main_window = self.get_service("main_window")
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 122, in get_service
    raise NotInitializedError("First call Application.init() to load services")
gaphor.application.NotInitializedError: First call Application.init() to load services
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 178, in app_shutdown
    self.shutdown()
  File "/app/lib/python3.7/site-packages/gaphor/application.py", line 130, in shutdown
    for name, srv in self.component_registry.get_utilities(IService):
AttributeError: 'NoneType' object has no attribute 'get_utilities'
```

**Comment by danyeaw** [comment]
@tronta This issue is now resolved, we will try to release a new version of Gaphor within the next couple of weeks with this fixed.

**Comment by danyeaw** [comment]
@all-contributors please add @tronta for bug

**Comment by danyeaw** [comment]
@all-contributors please add @tronta for bug

**Comment by stephanmol** [comment]
> @tronta This issue is now resolved, we will try to release a new version of Gaphor within the next couple of weeks with this fixed.

Any idea when a new version (this fix anyway) would be available in Gaphor's flatpak on https://flathub.org/apps/details/org.gaphor.Gaphor ? I cannot start/run Gaphor on Fedora 30 Silverblue on Wayland using Flatpak because without this new version/fix (so it seems)

Thanks for the hard work!

**Comment by danyeaw** [comment]
@stephanmol Sorry for the delay, and thanks for the reminder - this fell off my radar. We'll try to release a new version soon.
