### ISSUE TITLE
Creating a Comment Causes a KeyError

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1487]
### Describe the bug
I am getting `KeyError: None` any time I create a new comment.

### To Reproduce
1. Create a new UML model
2. Add a comment to a diagram

### Expected behavior
No KeyError.

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

### Additional information

Full traceback:
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/decorators.py", line 98, in async_wrapper
    func(*args, **kwargs)
  File "/home/dan/Projects/gaphor/gaphor/diagram/tools/placement.py", line 118, in open_editor
    InlineEditor(item, view, event_manager)
  File "/home/dan/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/dan/Projects/gaphor/gaphor/diagram/general/generaleditors.py", line 30, in CommentItemInlineEditor
    box = view.get_item_bounding_box(view.selection.hovered_item)
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/view/gtkview.py", line 287, in get_item_bounding_box
    *transform_rectangle(self._matrix, self._qtree.get_bounds(item))
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/quadtree.py", line 200, in get_bounds
    return self._ids[item][0]
KeyError: None
```

**Comment by amolenaar** [comment]
It was weird to see this issue, while it did not happen for things like Class.

Anyway, it's fixed now.

**Comment by danyeaw** [comment]
@amolenaar Thanks for the fix!
