### ISSUE TITLE
Exceptions when Renaming or Creating New Package or Diagram

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#149]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
It doesn't work to rename elements, or create new diagrams or packages in the Namespace.

### Expected behavior
Operations work as expected.

### Minimal reproduction of the problem with instructions
Create a new model. Right click on the root package, and select New package.

```
gaphor.transaction ERROR Transaction terminated due to an exception, performing a rollback
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/transaction.py", line 27, in _transactional
    r = func(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/gaphor/ui/namespace.py", line 600, in tree_view_create_diagram
    self.select_element(diagram)
  File "/app/lib/python3.7/site-packages/gaphor/ui/namespace.py", line 552, in select_element
    self._namespace.get_model().path_from_element(element)
AttributeError: 'TreeModelSort' object has no attribute 'path_from_element'
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gaphor/action.py", line 179, in _action_activate
    method()
  File "/app/lib/python3.7/site-packages/gaphor/transaction.py", line 27, in _transactional
    r = func(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/gaphor/ui/namespace.py", line 600, in tree_view_create_diagram
    self.select_element(diagram)
  File "/app/lib/python3.7/site-packages/gaphor/ui/namespace.py", line 552, in select_element
    self._namespace.get_model().path_from_element(element)
AttributeError: 'TreeModelSort' object has no attribute 'path_from_element'
``

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
There's a left-over from the old namespace code.
