### ISSUE TITLE
File Not Opening

### ISSUE THREAD

**Issue by codegeek007-sudo** [gaphor/gaphor#1495]
[BMS Example Gaphor.gaphor.zip](https://github.com/gaphor/gaphor/files/8592316/BMS.Example.Gaphor.gaphor.zip)

Unfortunately, I am unable to open the file. 

To replicate the issue, you can download the file and open it using the Gaphor Application. 

OS: MacOS 
Version: 2.9.2

**Comment by amolenaar** [comment]
Hi @codegeek007-sudo,

Thank you for raising this issue. I'll investigate.

**Comment by danyeaw** [comment]
Here is the traceback:

```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/filemanager.py", line 131, in async_loader
    for percentage in storage.load_generator(
  File "/home/dan/Projects/gaphor/gaphor/storage/storage.py", line 271, in load_generator
    for percentage in load_elements_generator(
  File "/home/dan/Projects/gaphor/gaphor/storage/storage.py", line 148, in load_elements_generator
    yield from _load_elements_and_canvasitems(
  File "/home/dan/Projects/gaphor/gaphor/storage/storage.py", line 192, in _load_elements_and_canvasitems
    create_element(elem)
  File "/home/dan/Projects/gaphor/gaphor/storage/storage.py", line 183, in create_element
    diagram_id = elem.references["diagram"]
KeyError: 'diagram'
Stack (most recent call last):
  File "/home/dan/Projects/gaphor/.venv/bin/gaphor", line 5, in <module>
    main()
  File "/home/dan/Projects/gaphor/gaphor/ui/__init__.py", line 90, in main
    run(argv)
  File "/home/dan/Projects/gaphor/gaphor/ui/__init__.py", line 151, in run
    gtk_app.run(args)
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/decorators.py", line 66, in async_wrapper
    next(iterator)
  File "/home/dan/Projects/gaphor/gaphor/ui/filemanager.py", line 145, in async_loader
    log.exception(f"Unable to open model “{filename}”.", stack_info=True)
> /home/dan/Projects/gaphor/gaphor/storage/storage.py(183)create_element()
-> diagram_id = elem.references["diagram"]
(Pdb) elem.references["diagram"]
*** KeyError: 'diagram'
(Pdb) elem.references
{'tail-connection': '152a2d6a-be86-11ec-805c-f24e9ffa0145'}
```

**Comment by amolenaar** [comment]
It's very odd. The model contains a whole bunch of `AssociationItem` elements without a relation to a diagram. When they are removed from a diagram, they should also removed from the model.

(`AssociationItem` is the element that's visible on the diagram)

@codegeek007-sudo Are you able to reproduce this?

I fixed the model. It should work for you now.

[BMS Example Gaphor.zip](https://github.com/gaphor/gaphor/files/8599061/BMS.Example.Gaphor.zip)

**Comment by amolenaar** [comment]
I'm not able to reproduce this issue. I expect it has something to do with the undo mechanism. How else can you create a `Presentation` without a diagram?

The undo mechanism has been simplified in the latest code (bd21b14cab0a622c354c67b42d47c3ebc4447c23 and ac6f6c396dde870716165c7ada475435915911a2, to be 2.10). That may be enough to avoid this issue in the future.

**Comment by amolenaar** [comment]
#1507 should also improve stability.

**Comment by amolenaar** [comment]
I expect this issue to be gone in 2.10.
