### ISSUE TITLE
GTK4 Comment Creates AttributeError

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1555]
### Describe the bug
GTK4 updated the Gtk.Frame api, and there is no longer an add method. Adding a comment while running gaphor with GTK4 causes an AttributeError.

```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/decorators.py", line 98, in async_wrapper
    func(*args, **kwargs)
  File "/home/dan/Projects/gaphor/gaphor/diagram/tools/placement.py", line 118, in open_editor
    InlineEditor(item, view, event_manager)
  File "/home/dan/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/dan/Projects/gaphor/gaphor/diagram/general/generaleditors.py", line 33, in CommentItemInlineEditor
    frame.add(text_view)
AttributeError: 'Frame' object has no attribute 'add'
```

### To Reproduce
1. `GAPHOR_USE_GTK4 gaphor`
2. Click on a comment in the toolbar and add it to the diagram

### Expected behavior
No Errors

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor:

**Comment by amolenaar** [comment]
This still needs fixing indeed.
