### ISSUE TITLE
RuntimeError when Deleting a Package or Diagram

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#160]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/services/undomanager.py", line 66, in execute
    action()
  File "/home/dan/Projects/gaphor/gaphor/services/undomanager.py", line 407, in _undo_association_delete_event
    association._set(element, value, from_opposite=True)
TypeError: _set() got an unexpected keyword argument 'from_opposite'
gaphor.services.undomanager ERROR Error while undoing action <function UndoManager.undo_association_set_event.<locals>._undo_association_set_event at 0x7f9d52ea67b8>
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/transaction.py", line 24, in _transactional
    r = func(*args, **kwargs)
  File "/home/dan/Projects/gaphor/gaphor/ui/namespace.py", line 678, in tree_view_delete_package
    package.unlink()
  File "/home/dan/Projects/gaphor/gaphor/UML/element.py", line 93, in unlink
    prop.unlink(self)
  File "/home/dan/Projects/gaphor/gaphor/UML/properties.py", line 444, in unlink
    value.unlink()
  File "/home/dan/Projects/gaphor/gaphor/UML/diagram.py", line 109, in unlink
    super(Diagram, self).unlink()
  File "/home/dan/Projects/gaphor/gaphor/UML/element.py", line 96, in unlink
    self._factory._unlink_element(self)
  File "/home/dan/Projects/gaphor/gaphor/UML/elementfactory.py", line 230, in _unlink_element
    self._handle(ElementDeleteEvent(self, element))
  File "/home/dan/Projects/gaphor/gaphor/UML/elementfactory.py", line 237, in _handle
    self.event_manager.handle(event)
  File "/home/dan/Projects/gaphor/gaphor/services/eventmanager.py", line 60, in handle
    self._events.handle(e)
  File "/home/dan/Projects/gaphor/gaphor/misc/generic/event.py", line 56, in handle
    for handler in handler_set:
RuntimeError: Set changed size during iteration
```

### Minimal reproduction of the problem with instructions
1. Open Gaphor
2. Right click on the main diagram
3. Delete the Diagram

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Fixed. I pushed the change to master directly, since it's quite trivial.
