### ISSUE TITLE
Error Loading Gtk.CustomFilter with GTK 3

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1603]
### Describe the bug

When I try to run gaphor from source in Windows, I am getting the following traceback:

```
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\greeter.py", line 179, in _on_template_activated
  |     session = self.application.new_session(template=translated_model)
  |   File "C:\Users\dan\Projects\gaphor\gaphor\application.py", line 93, in new_session
  |     return self._new_session(
  |   File "C:\Users\dan\Projects\gaphor\gaphor\application.py", line 119, in _new_session
  |     self.event_manager.handle(session_created)
  |   File "C:\Users\dan\Projects\gaphor\gaphor\core\eventmanager.py", line 64, in handle
  |     self._events.handle(queue.pop())
  |   File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\generic\event.py", line 61, in handle
  |     raise ExceptionGroup("Error while handling events", exceptions)
  | exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\generic\event.py", line 57, in handle
    |     handler(event)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\__init__.py", line 95, in on_session_created
    |     main_window.open(gtk_app)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\mainwindow.py", line 191, in open
    |     self.layout = deserialize(main_content, f.read(), _factory, self.properties)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\layout.py", line 54, in deserialize
    |     layout.append(_des(element, index, container))
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\layout.py", line 48, in _des
    |     _des(e, i, widget)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\layout.py", line 48, in _des
    |     _des(e, i, widget)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\layout.py", line 35, in _des
    |     widget = itemfactory(name)
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\mainwindow.py", line 187, in _factory
    |     return comp.open()
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\treecomponent.py", line 53, in open
    |     self.search_bar, self.search_filter = create_search_bar()
    |   File "C:\Users\dan\Projects\gaphor\gaphor\ui\treecomponent.py", line 285, in create_search_bar
    |     search_filter = Gtk.CustomFilter.new(name_filter)
    |   File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\gi\overrides\__init__.py", line 32, in __getattr__
    |     return getattr(self._introspection_module, name)
    |   File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\gi\module.py", line 123, in __getattr__
    |     raise AttributeError("%r object has no attribute %r" % (
    | AttributeError: 'gi.repository.Gtk' object has no attribute 'CustomFilter'
```

### To Reproduce
1. Launch Gaphor
2. Select to create a new model

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.11.0

**Comment by amolenaar** [comment]
Gtk.CustomFilter is a GTK4 thing. This error does not occur with our installer, right?

**Comment by danyeaw** [comment]
Installer works great

**Comment by amolenaar** [comment]
@danyeaw Is this still an issue? If so, how to reproduce? Build GTK4 on windows and run gaphor?
