### ISSUE TITLE
Unicode Decode Error in Windows with GTK4

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1611]
### Describe the bug
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 6: invalid start byte
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
Traceback (most recent call last):
  File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\gi\overrides\__init__.py", line 351, in wrap
    return func(a, b, *user_data)
  File "C:\Users\dan\Projects\gaphor\gaphor\ui\treemodel.py", line 79, in tree_item_sort
    nb = GLib.utf8_collate_key(b.text, -1).lower()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 6: invalid start byte
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
Traceback (most recent call last):
  File "C:\Users\dan\Projects\gaphor\.venv\lib\site-packages\gi\overrides\__init__.py", line 351, in wrap
    return func(a, b, *user_data)
  File "C:\Users\dan\Projects\gaphor\gaphor\ui\treemodel.py", line 79, in tree_item_sort
    nb = GLib.utf8_collate_key(b.text, -1).lower()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 6: invalid start byte
```

### To Reproduce
1. Create a Class (or any element) and add it to a diagram

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: main

**Comment by amolenaar** [comment]
Fixed by #1594.
