### ISSUE TITLE
Unable to Launch macOS App

### ISSUE THREAD

**Issue by nimo23** [gaphor/gaphor#1708]
### Describe the bug
I tried to open `Gaphor.App` on Mac OS (v 10.14.6) but it does not open and no warning or error is shown.

### Expected behavior
The app should be opened or at least provide a feedback to the user why this app cannot be opened.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS v 10.14.6
- [ ] Windows

### Version
Version of Gaphor: 2.11.0

**Comment by amolenaar** [comment]
Hi @nimo23, Thank you for your feedback. What type of mac are you using? An Intel-based or one of the new ARM based machines?

Are your security settings set properly? This app is not available in the App Store, so your security settings should be set to "App Store and identified developers".

<img width="600" alt="image" src="https://user-images.githubusercontent.com/96249/188319017-a804c73d-137d-484e-bd69-a153256947a4.png">

**Comment by amolenaar** [comment]
Oh wait. macOS 10.14. We're building our images on macOS 11. I'm running macOS 12.5.1 myself.

If you start Gaphor from the command line (Terminal or iTerm), does it say anything? You can start Gaphor by executing:

```
/Applications/Gaphor.app/Contents/MacOS/gaphor-exe
```

**Comment by nimo23** [comment]
>What type of mac are you using? 

An Intel-based

>If you start Gaphor from the command line (Terminal or iTerm), does it say anything? 

Yes, the error is clear now:

```
~ » /Applications/Gaphor.app/Contents/MacOS/gaphor-exe        
..
Traceback (most recent call last):
  File "_packaging/gaphor-script.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "gaphor/ui/__init__.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/_mac_detect.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so
[46874] Failed to execute script 'gaphor-script' due to unhandled exception: dlopen(/Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so
[46874] Traceback:
Traceback (most recent call last):
  File "_packaging/gaphor-script.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "gaphor/ui/__init__.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/_mac_detect.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Gaphor.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so
```

The line `..which was built for Mac OS X 10.15..` indicates that Gaphor requires at least Mac OS 10.15.

**Comment by amolenaar** [comment]
@nimo23 Thank you. I'll add it to our download page.
