### ISSUE TITLE
Invalid Matrix error when adding Use Case to diagram

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1713]
### Describe the bug
Adding a Use Case to a digram creates an invalid matrix error.

### To Reproduce
1. Open Gaphor
2. Select a Use Case from the toolbox and add it to the diagram

```
|Traceback (most recent call last):
|  File "/home/dan/Projects/gaphor/gaphor/diagram/painter.py", line 33, in paint_item
|    item.draw(
|  File "/home/dan/Projects/gaphor/gaphor/diagram/presentation.py", line 151, in draw
|    self._shape.draw(
|  File "/home/dan/Projects/gaphor/gaphor/diagram/shapes.py", line 173, in draw
|    self._draw_border(self, new_context, bounding_box)
|    │                 │     │            └ Rectangle()
|    │                 │     └ DrawContext(cairo=<cairo.Context object at 0x7f8d8b9db2f0>, style={'background-color': (0.0, 0.0, 0.0, 0.0), 'color': (0.0, 0.24...
|    │                 └ <gaphor.diagram.shapes.Box object at 0x7f8d72558fd0>
|    └ <gaphor.diagram.shapes.Box object at 0x7f8d72558fd0>
|  File "/home/dan/Projects/gaphor/gaphor/UML/usecases/usecase.py", line 42, in draw_usecase
|    path_ellipse(cr, rx, ry, bounding_box.width, bounding_box.height)
|    │            │   │   │   │                   └ Rectangle()
|    │            │   │   │   └ Rectangle()
|    │            │   │   └ 0.0
|    │            │   └ 0.0
|    │            └ <cairo.Context object at 0x7f8d8b9db2f0>
|    └ <function path_ellipse at 0x7f8db063c5e0>
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/util.py", line 121, in path_ellipse
|    cr.scale(width / 2.0, height / 2.0)
|    │        │            └ 0.0
|    │        └ 0.0
|    └ <cairo.Context object at 0x7f8d8b9db2f0>
|cairo.Error: invalid matrix (not invertible)
```

### Expected behavior
No error

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

### Additional information
OS: Linux (5.19.2-1-default)
Python version: 3.10.6
GTK version: 4.7.2
Display: GdkWaylandDisplay
Gaphor version: 2.11.0

**Comment by amolenaar** [comment]
I replaced the arc + scale with a bezier curve.
