### ISSUE TITLE
Error report when moving a box

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#1743]
### Describe the bug

An error report appears when moving a box.

### To Reproduce
1. Create a new model, select UML
2. Open the `1. Use Cases` diagram
3. Select to "box/rectangle"  general tool, and draw a box
4. Select the cursor general tool, and move the box from (3)

This produces this error report:
```
OS: Linux (5.19.9-200.fc36.x86_64)
Python version: 3.9.9
GTK version: 3.24.34
Gaphor version: 2.11.0

Errors:

Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 366.0
|    │            └ 619.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 345.0
|    │            └ 615.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 322.0
|    │            └ 608.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 279.0
|    │            └ 591.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 108.0
|    │            └ 523.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
Time since application startup: 1:14:07
|Traceback (most recent call last):
|  File "/app/lib/python3.9/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 105.0
|    │            └ 521.0
|    └ <gaphor.diagram.tools.dropzone.DropZoneMove object at 0x7f0961cc4fa0>
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/tools/dropzone.py", line 96, in move
|    if can_group(over_item.subject, item.subject):
|  File "/app/lib/python3.9/site-packages/gaphor/diagram/group.py", line 50, in can_group
|    for t1, t2 in itertools.product(parent_mro, element_type.__mro__):
|AttributeError: 'NoneType' object has no attribute '__mro__'
└─────────────────────────────╌┄┈
```

### Expected behavior

There should not be an error popup when moving a box.

### Screenshots

Video : 
[Capture vidéo du 21-09-2022 11:22:17.webm](https://user-images.githubusercontent.com/5868014/191467671-4e892d0b-9bff-44b0-94f5-ee5c5118f388.webm)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

Fedora 36 running GNOME 42.4

### Version
Version of Gaphor: 2.11.0 (Flatpak)

**Comment by amolenaar** [comment]
Hi @ebousse, thank you for reporting. Just in time to be fixed before we release 2.12. 😀
