### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'main_quit'

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1915]
### Describe the bug
There is a GTK3 specific call in one of the tests:

```
Traceback (most recent call last):
  File "C:\Users\dan\Projects\gaphor\tests\test_load_model.py", line 41, in handler
    Gtk.main_quit()
    ^^^^^^^^^^^^^
  File "C:\Users\dan\Projects\gaphor\.venv\Lib\site-packages\gi\overrides\__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\Projects\gaphor\.venv\Lib\site-packages\gi\module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'main_quit'
```

Can we remove the finally block?

### To Reproduce
1. Once when running all the tests in Windows got this error in the gaphor-self-test.txt.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor:

**Comment by amolenaar** [comment]
By looking at the tests they do not test anything useful: there are a lot of tests that load a model. I propose to remove the test.
