### ISSUE TITLE
Gaphor installed with pip on Ubuntu 18.04 does not run

### ISSUE THREAD

**Issue by ruimaciel** [gaphor/gaphor#196]
### I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
After Gaphor is installed with pip in Ubuntu 18.04, Gaphor does not run.

### Expected behavior

Gaphor running.

### Minimal reproduction of the problem with instructions

* get an Ubuntu 18.04 instance

* install all the required packages  (see https://github.com/gaphor/gaphor/issues/141)
    `$ sudo apt install libcairo2-dev libgirepository1.0-dev libpython3-dev`

* Create and prepare a python3 virtual environment
    `$ mkdir gaphor-test && cd gaphor-test`
    `$ python3 -m venv venv`
    `$ source venv/bin/activate`
    `$ pip install pip --upgrade`

* Install Gaphor with pip
    `$ pip install gaphor`

* Finally, run Gaphor
    `$ gaphor`

### System Information
OS:
- [x] Linux (Ubuntu 18.04)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by danyeaw** [comment]
@ruimaciel Thanks for the bug report. Does it just close immediately? Are there any errors? Are you using Wayland or X11?

**Comment by danyeaw** [comment]
One more thing that I thought of, are you using the Python that ships with Ubuntu? Ubuntu 18.04 has Python 3.5, and we are using Python 3.6+ syntax including f-strings and other Features. We really only test using the latest version of Python (3.7.4 at this moment). If you are using the Python that ships with Ubuntu 18.04, you could install a newer version using [pyenv](https://github.com/pyenv/pyenv). Alternatively if you are just trying to run Gaphor, you could install it using the Flatpak.

**Comment by danyeaw** [comment]
@ruimaciel Is this still an issue?

**Comment by ruimaciel** [comment]
I've just checked and unfortunately it is still an issue: gaphor fails to run after being installed with pip.

Ubuntu 18.04 ships with Python 3.6.8.

```
(venv) rui@rui-desktop:gaphor$ gaphor                                                                                                                                                                                                              
                                                                                                                                                                                                                                                   
(gaphor:11159): Gtk-WARNING **: 13:16:30.711: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version                            
                                                                                                                                                                                                                                                   
(gaphor:11159): Gtk-WARNING **: 13:16:30.711: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version                            
                                                                                                                                                                                                                                                   
(gaphor:11159): Gtk-WARNING **: 13:16:30.711: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version                 
Traceback (most recent call last):                                                                                                                                                                                                                 
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 119, in app_startup
    self.init()
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 49, in init
    self.load_services(services)
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 59, in load_services
    cls = ep.load()
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/plugins/alignment/__init__.py", line 7, in <module>
    from gaphor.ui.event import DiagramSelectionChange
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/ui/__init__.py", line 11, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'
Traceback (most recent call last):
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 124, in app_activate
    main_window = self.get_service("main_window")
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 84, in get_service
    raise NotInitializedError("First call Application.init() to load services")
gaphor.application.NotInitializedError: First call Application.init() to load services
Traceback (most recent call last):
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 136, in app_shutdown
    self.shutdown()
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 89, in shutdown
    for srv, name in self.component_registry.all(Service):
AttributeError: 'NoneType' object has no attribute 'all'
(venv) rui@rui-desktop:gaphor$ python --version
Python 3.6.8
```

**Comment by danyeaw** [comment]
@ruimaciel since you are using Python 3.6, you need to `pip install importlib_resources`. This is part of the standard library in Python 3.7, and that PyPI package is a backport for previous Python versions. If you want to run gaphor from source, I would highly recommend installing Python 3.7 using pyenv, and then follow the instructions to setup a development environment in the README. Maybe we could make the README more clear that the latest stable Python is required. If you need help setting things up, the Gitter chat room might be easier to chat on.

**Comment by ruimaciel** [comment]
I've installed importlib_resources and gaphor still crashes.


```
(venv) rui@rui-desktop:gaphor$ pip install importlib_resources
Collecting importlib_resources
  Using cached https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl
Installing collected packages: importlib-resources
Successfully installed importlib-resources-1.0.2
(venv) rui@rui-desktop:gaphor$ gaphor

(gaphor:15640): Gtk-WARNING **: 15:29:40.474: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gaphor:15640): Gtk-WARNING **: 15:29:40.474: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gaphor:15640): Gtk-WARNING **: 15:29:40.474: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 119, in app_startup
    self.init()
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 49, in init
    self.load_services(services)
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 59, in load_services
    cls = ep.load()
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/plugins/alignment/__init__.py", line 7, in <module>
    from gaphor.ui.event import DiagramSelectionChange                                                                                                                                                                                             
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/ui/__init__.py", line 11, in <module>                                                                                                                          
    import importlib.resources                                                                                                                                                                                                                     
ModuleNotFoundError: No module named 'importlib.resources'                                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                                                 
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 124, in app_activate                                                                                                                     
    main_window = self.get_service("main_window")                                                                                                                                                                                                  
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 84, in get_service                                                                                                                       
    raise NotInitializedError("First call Application.init() to load services")                                                                                                                                                                    
gaphor.application.NotInitializedError: First call Application.init() to load services                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                                                 
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 136, in app_shutdown                                                                                                                     
    self.shutdown()                                                                                                                                                                                                                                
  File "/home/rui/development/python/gaphor/venv/lib/python3.6/site-packages/gaphor/application.py", line 89, in shutdown                                                                                                                          
    for srv, name in self.component_registry.all(Service):                                                                                                                                                                                         
AttributeError: 'NoneType' object has no attribute 'all' 
```

If gaphor is not expected to run on Ubuntu 18.04, much less installed on Ubuntu 18.04 with pip, then perhaps it would be best to remove that reference from [gaphor's  README.md](https://github.com/gaphor/gaphor/blob/master/README.md).  Additionally, gaphor's README.md doesn't mention anywhere that it is only expected to run on Python 3, let alone Python 3.7.*, which might create some problems and generate some unwanted chatter on the project's issues page.

**Comment by danyeaw** [comment]
@ruimaciel Thanks for pointing out that issue with the README. I have updated it with hopefully more clear instructions. The nice thing about using the flatpak with Linux, is that you don't have to worry about any of the dependencies, they are all packaged with the flatpak.
