### ISSUE TITLE
Double click to add element to diagram raises exception

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2038]
### Describe the bug

```
Original exception was:
Traceback (most recent call last):
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/decorators.py", line 86, in async_wrapper
    func(*args, **kwargs)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 317, in update
    self.update_bounding_box(dirty_items)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 354, in update_bounding_box
    painter.paint_item(item, cr)
  File "/home/arjan/Development/gaphor/gaphor/diagram/painter.py", line 25, in paint_item
    style = diagram.style(StyledItem(item, selection))
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'style'
```

### To Reproduce
1. Open a diagram
2. Double-click on an element in the model browser, exept for a diagram
3. The system is confused and undo-manager blocks any future actions

### Version
Version of Gaphor: 2.14?

**Comment by amolenaar** [comment]
@danyeaw This was a nasty issue.
