### ISSUE TITLE
Gaphor freezes creating a new diagram

### ISSUE THREAD

**Issue by mcdigregorio** [gaphor/gaphor#2101]
### Describe the bug
Unable to create diagrams without computer freezing for several minutes.
From what I can tell it seems to be isolated the dmg image itself.

### To Reproduce
1. Right click the side bar and select a diagram from the "New Diagram" menu, or create a new digram from the dedicated "Create New Diagram" button

> If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

Trying to query the error report actually freezes gaphor as well.

### Expected behavior
New diagram to be created with minimal delay.

### Screenshots
<img width="858" alt="Screenshot 2023-02-23 at 7 23 09 AM" src="https://user-images.githubusercontent.com/17177951/220905524-a3dd7d09-4698-456a-8751-3e01ddbf47c7.png">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.16.0

### Additional information
If I pull down the 2.16.0 tag and run from source I do not have the same issues.

**Comment by amolenaar** [comment]
Hi @mcdigregorio, thank you very much for your report.

I can reproduce this issue, both with 2.15.0 and the main branch.

This issue only arises with GTK+3, the GTK4 version works fine.

In the logging, a lot of exceptions are thrown:

```
  + Exception Group Traceback (most recent call last):
  |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 183, in rollback_transaction
  |     erroneous_tx.execute()
  |   File "/Users/arjan/Development/gaphor/gaphor/transaction.py", line 169, in _transactional
  |     return func(*args, **kwargs)
  |            ^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 71, in execute
  |     act()
  |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 372, in undo_attribute_change_event
  |     attribute.set(element, value)
  |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/properties.py", line 240, in set
  |     self.handle(AttributeUpdated(obj, self, old, value))
  |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/properties.py", line 181, in handle
  |     event.element.handle(event)
  |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/element.py", line 174, in handle
  |     model.handle(event)
  |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/elementfactory.py", line 225, in handle
  |     self.event_manager.handle(event)
  |   File "/Users/arjan/Development/gaphor/gaphor/core/eventmanager.py", line 77, in handle
  |     self._priority.handle(event)
  |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 61, in handle
  |     raise ExceptionGroup("Error while handling events", exceptions)
  | ExceptionGroup: Error while handling events (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 57, in handle
    |     handler(event)
    |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 379, in undo_attribute_change_event
    |     self.add_undo_action(undo_attribute_change_event)
    |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 139, in add_undo_action
    |     self._action_executed()
    |   File "/Users/arjan/Development/gaphor/gaphor/services/undomanager.py", line 266, in _action_executed
    |     self.event_manager.handle(ActionEnabled("win.edit-undo", self.can_undo()))
    |   File "/Users/arjan/Development/gaphor/gaphor/core/eventmanager.py", line 83, in handle
    |     self._events.handle(queue.pop())
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 61, in handle
    |     raise ExceptionGroup("Error while handling events", exceptions)
    | ExceptionGroup: Error while handling events (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 57, in handle
      |     handler(event)
      |   File "/Users/arjan/Development/gaphor/gaphor/ui/diagrams.py", line 389, in _on_name_change
      |     elif event.element is widget.get_child().diagram_page.diagram:
      |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'GtkView' object has no attribute 'diagram_page'
      +------------------------------------
```

**Comment by amolenaar** [comment]
@mcdigregorio Gaphor 2.17 has been released. The issue has been fixed in this release.

**Comment by mcdigregorio** [comment]
@amolenaar Working great on my end, thanks for the fix.

**Comment by danyeaw** [comment]
@all-contributors please add @mcdigregorio for bug
