### ISSUE TITLE
TypeError: Disconnecting a Connector with an ItemFlow

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2127]
### Describe the bug
Sorry for all the issues submitted today, but dog fooding is causing me to find some issues :see_no_evil:.

I am getting a TypeError when disconnecting a connector with an ItemFlow without an Item Property.

### To Reproduce
1. Create two Properties on a diagram
2. Add a Connector between them
3. Enable Item Flow in the property page
4. Disconnect the connector from one end

```
gaphor.ui.elementeditor ERROR Could not construct property page for ItemFlowPropertyPage
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/elementeditor.py", line 178, in create_pages
    page = adapter.construct()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/Projects/gaphor/gaphor/SysML/propertypages.py", line 207, in construct
    self.entry.set_text(iflow.itemProperty.name)
TypeError: Argument 1 does not allow None as a value
```

### Expected behavior
No Error

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

**Comment by amolenaar** [comment]
@danyeaw I performed the steps you described, but I can't reproduce this.
