### ISSUE TITLE
Reorder diagram tabs raises error

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2177]
### To Reproduce
1. Open a model with multiple diagrams
2. Open 3 diagrams
3. Move one tab to another place
4. Close the other tabs
5. See error as soon as you move the cursor over the diagram
6. Note that the diagram remains blank (closing and opening it again will fix this)

```
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
Traceback (most recent call last):
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/tool/hover.py", line 23, in on_motion
    item, handle = find_item_and_handle_at_point(view, pos)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/tool/itemtool.py", line 98, in find_item_and_handle_at_point
    item, handle = handle_at_point(view, pos)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/tool/itemtool.py", line 181, in handle_at_point
    view.get_items_in_rectangle(
  File "/home/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 270, in get_items_in_rectangle
    assert self._model
AssertionError
```

### Expected behavior

Reorder of tabs should just work, diagrams should remain drawn

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

**Comment by amolenaar** [comment]
Fixed in Gaphas 3.10.2.
