### ISSUE TITLE
Double-clicking on a diagram element bug

### ISSUE THREAD

**Issue by Linuxiness** [gaphor/gaphor#2304]
### Describe the bug
Double-clicking on a diagram element does not show in the Diagram section.

### OS
- [x] Linux (Manjaro, Appimage)

### Version
Version of Gaphor: 2.18.0

### Additional information
```
Gaphor version:    2.18.0
Operating System:  Linux (5.10.174-1-MANJARO)
Python version:    3.10.9
GTK version:       4.8.3
Adwaita version:   1.2.2
PyGObject version: 3.42.2
Pycairo version:   1.23.0
Cairo version:     1.17.8
Pango version:     1.50.12
Display:           X11Display


Errors:

Time since application startup: 9:48:05
|Traceback (most recent call last):
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 84, in list_view_activate
|    self.open_element(element)
|    │                 └ <gaphor.UML.uml.Message element 7c46ea76-f2ae-11ed-8705-10f0059ea926>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 139, in open_element
|    self.event_manager.handle(ElementOpened(element))
|    │                         │             └ <gaphor.UML.uml.Message element 7c46ea76-f2ae-11ed-8705-10f0059ea926>
|    │                         └ <class 'gaphor.ui.event.ElementOpened'>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/core/eventmanager.py", line 83, in handle
|    self._events.handle(queue.pop())
|    │                   └ deque([])
|    └ <gaphor.core.eventmanager.EventManager object at 0x7f39d2befdc0>
|  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 61, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|          │                                             └ [AssertionError()]
|          └ <class 'exceptiongroup.ExceptionGroup'>
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 57, in handle
  |    handler(event)
  |    │       └ <gaphor.ui.event.ElementOpened object at 0x7f39ba695ff0>
  |    └ <bound method Diagrams._on_show_element of <gaphor.ui.diagrams.Diagrams object at 0x7f39e8b2fa00>>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/diagrams.py", line 231, in _on_show_element
  |    if item := drop(event.element, diagram, x, y):
  |  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
  |    return dispatch(args[0].__class__)(*args, **kw)
  |           │        │                   │       └ {}
  |           │        │                   └ (<gaphor.UML.uml.Message element 7c46ea76-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           │        └ (<gaphor.UML.uml.Message element 7c46ea76-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           └ <function singledispatch.<locals>.dispatch at 0x7f39f00c7d90>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/drop.py", line 48, in drop_message
  |    assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  |                      │                  └ <module 'gaphor.UML' from '/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/__init__.py'>
  |                      └ <gaphor.UML.uml.Message element 7c46ea76-f2ae-11ed-8705-10f0059ea926>
  |AssertionError: assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  └─────────────────────────────╌┄┈
Time since application startup: 9:48:07
|Traceback (most recent call last):
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 84, in list_view_activate
|    self.open_element(element)
|    │                 └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 139, in open_element
|    self.event_manager.handle(ElementOpened(element))
|    │                         │             └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
|    │                         └ <class 'gaphor.ui.event.ElementOpened'>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/core/eventmanager.py", line 83, in handle
|    self._events.handle(queue.pop())
|    │                   └ deque([])
|    └ <gaphor.core.eventmanager.EventManager object at 0x7f39d2befdc0>
|  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 61, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|          │                                             └ [AssertionError()]
|          └ <class 'exceptiongroup.ExceptionGroup'>
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 57, in handle
  |    handler(event)
  |    │       └ <gaphor.ui.event.ElementOpened object at 0x7f39d3aed480>
  |    └ <bound method Diagrams._on_show_element of <gaphor.ui.diagrams.Diagrams object at 0x7f39e8b2fa00>>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/diagrams.py", line 231, in _on_show_element
  |    if item := drop(event.element, diagram, x, y):
  |  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
  |    return dispatch(args[0].__class__)(*args, **kw)
  |           │        │                   │       └ {}
  |           │        │                   └ (<gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           │        └ (<gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           └ <function singledispatch.<locals>.dispatch at 0x7f39f00c7d90>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/drop.py", line 48, in drop_message
  |    assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  |                      │                  └ <module 'gaphor.UML' from '/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/__init__.py'>
  |                      └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
  |AssertionError: assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  └─────────────────────────────╌┄┈
Time since application startup: 9:48:12
|Traceback (most recent call last):
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 84, in list_view_activate
|    self.open_element(element)
|    │                 └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/modelbrowser.py", line 139, in open_element
|    self.event_manager.handle(ElementOpened(element))
|    │                         │             └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
|    │                         └ <class 'gaphor.ui.event.ElementOpened'>
|    └ <gaphor.ui.modelbrowser.ModelBrowser object at 0x7f39bb1074c0>
|  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/core/eventmanager.py", line 83, in handle
|    self._events.handle(queue.pop())
|    │                   └ deque([])
|    └ <gaphor.core.eventmanager.EventManager object at 0x7f39d2befdc0>
|  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 61, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|          │                                             └ [AssertionError()]
|          └ <class 'exceptiongroup.ExceptionGroup'>
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/home/igor/.local/lib/python3.10/site-packages/generic/event.py", line 57, in handle
  |    handler(event)
  |    │       └ <gaphor.ui.event.ElementOpened object at 0x7f39d3aed9c0>
  |    └ <bound method Diagrams._on_show_element of <gaphor.ui.diagrams.Diagrams object at 0x7f39e8b2fa00>>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/ui/diagrams.py", line 231, in _on_show_element
  |    if item := drop(event.element, diagram, x, y):
  |  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
  |    return dispatch(args[0].__class__)(*args, **kw)
  |           │        │                   │       └ {}
  |           │        │                   └ (<gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           │        └ (<gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>, <gaphor.core.modeling.diagram.Diagram element 5c112830-f...
  |           └ <function singledispatch.<locals>.dispatch at 0x7f39f00c7d90>
  |  File "/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/drop.py", line 48, in drop_message
  |    assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  |                      │                  └ <module 'gaphor.UML' from '/home/igor/.local/lib/python3.10/site-packages/gaphor/UML/__init__.py'>
  |                      └ <gaphor.UML.uml.Message element 484bf1da-f2ae-11ed-8705-10f0059ea926>
  |AssertionError: assert isinstance(element.sendEvent, UML.MessageOccurrenceSpecification)
  └─────────────────────────────╌┄┈

```

**Comment by amolenaar** [comment]
Thanks. 

Can you help me out with a minimal example to reproduce the issue?

I think `MessageOccurrenceSpecification` is one of those "glue" objects that are not visible in the diagram, but I'll have to check.

**Comment by amolenaar** [comment]
Ah, thanks. The exception itself does no harm to the model. The messages are only connected on the head. The drop logic is too rigid and expects both ends to be connected.

Thanks for reporting :rocket:

**Comment by danyeaw** [comment]
@all-contributors please add @Linuxiness for bug

Thanks @Linuxiness for the report!

**Comment by danyeaw** [comment]
@all-contributors please add @Linuxiness for bug
