### ISSUE TITLE
AttributeError when deleting diagrams with elements

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2496]
### Describe the bug
I am getting the following AttributeError if I delete a diagram with elements on it.

```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/.venv/lib/python3.11/site-packages/gaphas/decorators.py", line 86, in async_wrapper
    func(*args, **kwargs)
  File "/home/dan/Projects/gaphor/.venv/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 319, in update
    self.update_bounding_box(dirty_items)
  File "/home/dan/Projects/gaphor/.venv/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 356, in update_bounding_box
    painter.paint_item(item, cr)
  File "/home/dan/Projects/gaphor/gaphor/diagram/painter.py", line 28, in paint_item
    style = diagram.style(StyledItem(item, selection, self.dark_mode))
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'style'
```

### To Reproduce
1. Open the Generic Model
2. Open the New diagram
3. Create a class on the diagram
4. Delete the New Diagram

### Expected behavior
No Error.

### OS
- [X] Linux
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: latest main

**Comment by amolenaar** [comment]
The painter is called asynchronously  after the diagram has been removed, it seems?
