### ISSUE TITLE
Opening a Recent File with a Space in the Path Raises FileNotFoundError

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#254]
Well, dogfooding helps me find bugs :dog2: 

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
If you save a model file in a directory with a space in the name, and then open it from the Recently used files, Gaphor crashes.

The issue is that the space in the filename is getting converted into a %20, and then not unquoted when opening up the filename. This may be caused by `Gio.File.get_uri()` which is called from the RecentFilesMenu class in the mainwindow module.

### Expected behavior
Gaphor is able to open files with a space in the filename

### Minimal reproduction of the problem with instructions

1. Create a directory with a space in the name
1. Create a new model, and save it to the directory above
1. Close Gaphor and reopen it
1. Select the file from the Recently opened files dialog
1. Gaphor crashes.

```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/misc/gidlethread.py", line 127, in __generator_executer
    result = next(self._generator)
  File "/home/dan/Projects/gaphor/gaphor/storage/storage.py", line 305, in load_generator
    for percentage in parser.parse_generator(filename, loader):
  File "/home/dan/Projects/gaphor/gaphor/storage/parser.py", line 318, in parse_generator
    yield from parse_file(filename, parser)
  File "/home/dan/Projects/gaphor/gaphor/storage/parser.py", line 371, in parse_file
    file_obj = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: b'/home/dan/Documents/MBSE%20Hackers/sysml.gaphor'
```

### System Information
OS:
- [X] Linux - Ubuntu 19.10
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
@amolenaar Thanks for quickly resolving this :+1:, I hadn't gotten a chance to dig in to it yet.

**Comment by danyeaw** [comment]
@amolenaar Builds were failing in Windows due to translation of path names in to backspaces, pathlib to the rescue with eadf9bf.
