### ISSUE TITLE
Interface object is not subscriptable

### ISSUE THREAD

**Issue by matzipan** [gaphor/gaphor#2650]
### Describe the bug

```
Traceback (most recent call last):
  File "/lhome/andzisu/Workspace/architect_tool/bla.py", line 22, in <module>
    if hasattr(element, "required"):
  File "/lhome/andzisu/.local/lib/python3.10/site-packages/gaphor/UML/umloverrides.py", line 133, in component_required
    return list(itertools.chain(usages, *rc_usages))
  File "/lhome/andzisu/.local/lib/python3.10/site-packages/gaphor/UML/umloverrides.py", line 89, in <genexpr>
    if dep.isKindOf(dep_type) and dep.supplier[0].isKindOf(uml.Interface)
TypeError: 'Interface' object is not subscriptable
```

It appears that `dep.supplier` is of interface type `uml.Interface` and no indexing is necessary.

### To Reproduce

1. Create a diagram with 2 components (A and B) and 1 interface
2. Add dependency between component B and interface, automatically goes to "Use"
3. Add dependency between interface and component A automatically goes to "Realize".
4. Run the following script:

```
from gaphor.core.modeling import ElementFactory
element_factory = ElementFactory()

from gaphor.core.eventmanager import EventManager
from gaphor.services.modelinglanguage import ModelingLanguageService
from gaphor.storage import storage

event_manager = EventManager()
modeling_language = ModelingLanguageService(event_manager=event_manager)
with open("diagram.gaphor") as file_obj:
    storage.load(
        file_obj,
        element_factory,
        modeling_language,
    )
    from gaphor import UML
    for element in element_factory.lselect():
        if hasattr(element, "name"):
            print(element.name)
        if hasattr(element, "provided"):
            print(element.provided)
        if hasattr(element, "required"):
            print(element.required)
```

### Expected behavior

It will print:

```
New model
New Component Diagram
A
New Interface
B
New Interface
```

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20.0
Flatpak on Ubuntu 22.04

**Comment by danyeaw** [comment]
@all-contributors please add @matzipan for bug

**Comment by danyeaw** [comment]
Thanks @matzipan for submitting this issue!

**Comment by matzipan** [comment]
Thanks for the quick response.

Nice code base. Happy that I could understand the thought behind the code so easily. Next time I will try to submit a fix too.
