### ISSUE TITLE
Double click with composite association on the diagram shows error

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2674]
### Describe the bug

Double click with composite association on the diagram shows error.

### To Reproduce
1. Create a diagram
2. Select composite assocation
3. Double click on the diagram anywhere
4. Error is being displayed

Gaphor version:         2.20.0
Operating System:       Linux (6.2.0-27-generic)
Display:                X11Display
Python version:         3.11.2
GTK version:            4.10.4
Adwaita version:        1.3.3
GtkSourceView version:  5.8.0
Cairo version:          1.16.0
Pango version:          1.50.12
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4

Errors:

Time since application startup: 0:01:02
|Traceback (most recent call last):
|  File "/home/zsolt/Development/github/gaphor-dev/gaphor/gaphor/diagram/tools/placement.py", line 105, in on_drag_end
|    connect_opposite_handle(view, item, x, y, placement_state.handle_index)
|    │                       │     │     │  │  └ <gaphor.diagram.tools.placement.PlacementState object at 0x7fc850456d50>
|    │                       │     │     │  └ 0.0
|    │                       │     │     └ 0.0
|    │                       │     └ <gaphor.UML.classes.association.AssociationItem element 2ab477b1-43e3-11ee-99bb-48a4721e5d5c>
|    │                       └ None
|    └ <function connect_opposite_handle at 0x7fc852e3fec0>
|  File "/home/zsolt/Development/github/gaphor-dev/gaphor/gaphor/diagram/tools/placement.py", line 89, in connect_opposite_handle
|    if handle_move.glue(vpos):
|  File "/home/zsolt/Development/github/gaphor-dev/gaphor/gaphor/diagram/tools/handlemove.py", line 48, in glue
|    sink = super().glue(pos, distance)  # type: ignore[misc]
|                        │    └ 10
|                        └ (0.0, 0.0)
|  File "/home/zsolt/.cache/pypoetry/virtualenvs/gaphor-8V5dvryD-py3.11/lib/python3.11/site-packages/gaphas/handlemove.py", line 71, in glue
|    model = view.model
|            └ None
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈

### Expected behavior

It should not display and error.

### OS
- [X] Linux (Ubuntu latest)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: Latest main

**Comment by sz332** [comment]
Looks like the exception is coming from gaphas. @amolenaar ?

**Comment by amolenaar** [comment]
It does. However, I am not able to reproduce this issue.

**Comment by sz332** [comment]
On Linux, just select a tool and quickly double click on the canvas, this is how I could trigger the issue very stable.
