### ISSUE TITLE
Error moving a diagram to the root

### ISSUE THREAD

**Issue by alensiljak** [gaphor/gaphor#2734]
### Describe the bug
It is not possible to move a diagram into the root of the model.

### To Reproduce
1. Create a diagram as a child of another item in the model tree (not sure how but by default the Activity diagram was under the Relationships).
2. Create a new diagram by using the + menu. This one ends in the root.
3. Move the first diagram into the root of the model by dragging it under the second one.

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.
```
Gaphor version:         2.21.0
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.5
GTK version:            4.12.0
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4


Errors:

Time since application startup: 0:13:39
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\modelbrowser.pyc", line 589, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 0:13:47
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\modelbrowser.pyc", line 589, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 0:15:06
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\modelbrowser.pyc", line 582, in list_item_drop_drop
|AttributeError: 'NoneType' object has no attribute 'owner'
└─────────────────────────────╌┄┈
Time since application startup: 0:17:07
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\modelbrowser.pyc", line 589, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
```
### Expected behavior
The element (a diagram in this case) should end up in the root, like the ones created from the menu.

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/462445/26c6ae7b-39fd-4295-a327-d9e72eaa8740)

### OS
- [x] Windows

### Version
Version of Gaphor: 2.21.0

**Comment by amolenaar** [comment]
Thanks @alensiljak, I can reproduce this issue.

**Comment by danyeaw** [comment]
Thanks @alensiljak for the bug report!
