### ISSUE TITLE
Cancelling out of drawing a relationship causes an exception

### ISSUE THREAD

**Issue by alensiljak** [gaphor/gaphor#2736]
### Describe the bug
Pressing ESC to exit the creation of a relationship causes an exception.

### To Reproduce
1. Create a diagram
2. Add Class 1
3. Add Class 2
4. Select a relationship and start drawing from the Class 1.
5. Before reaching the Class 2, press Escape to cancel out the operation
6. Observe the error.

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.
```
Gaphor version:         2.21.0
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.5
GTK version:            4.12.0
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4


Errors:

Time since application startup: 0:02:17
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\placement.pyc", line 105, in on_drag_end
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\placement.pyc", line 89, in connect_opposite_handle
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\handlemove.pyc", line 48, in glue
|  File "C:\Program Files\Gaphor\gaphas\handlemove.pyc", line 71, in glue
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 0:02:25
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\placement.pyc", line 105, in on_drag_end
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\placement.pyc", line 89, in connect_opposite_handle
|  File "C:\Program Files\Gaphor\gaphor\diagram\tools\handlemove.pyc", line 48, in glue
|  File "C:\Program Files\Gaphor\gaphas\handlemove.pyc", line 71, in glue
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈

```
### Expected behavior
The operation should be canceled and the incomplete relationship removed from the model.

### OS
- [x] Windows

### Version
Version of Gaphor: 2.21.0

**Comment by alensiljak** [comment]
If we are drawing a new relationship, I think it would be OK to completely cancel it.
Thanks for handling this!

**Comment by 0lione** [comment]
Is this issue fixed? I can't reproduce it.
