### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by jl2035** [gaphor/gaphor#2825]
### Describe the bug
Pip installation is successful, but the program does not start. It complains with the following exception:

```
Traceback (most recent call last):
  File "/home/user/Prog/gaphor/bin/gaphor", line 8, in <module>
    sys.exit(main())
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gaphor/main.py", line 21, in main
    commands: dict[str, argparse.ArgumentParser] = initialize("gaphor.argparsers")
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gaphor/entrypoint.py", line 13, in initialize
    return init_entry_points(load_entry_points(scope, services), **known_services)
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gaphor/entrypoint.py", line 29, in load_entry_points
    cls = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gaphor/plugins/diagramexport/__init__.py", line 15, in <module>
    from gaphor.ui.filedialog import save_file_dialog
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gaphor/ui/__init__.py", line 11, in <module>
    gi.require_version("GtkSource", "5")
  File "/home/user/Prog/gaphor/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 5
```

### To Reproduce
1. Install virtualenv
2. source bin/activate
3. pip install gaphor
4. gaphor

### Expected behavior
The program should start.

### OS
- [x] Linux (Ubuntu 22.04.3 LTS)

### Version
Version of Gaphor: gaphor-2.21.0

**Comment by amolenaar** [comment]
Hi @jl2035, thank you for reaching out.

Your missing GtkSourceView.

Did you check our documentation on installing dependencies for Gaphor? The page https://docs.gaphor.org/en/latest/linux.html tells you which packages you need to install on Ubuntu.

**Comment by danyeaw** [comment]
Hi @jl2035, I'm assuming this was because you were missing a dependency like @amolenaar said. If you install GtkSourceView and you are still having issues, feel free to open back up the issue. Thanks!

**Comment by jl2035** [comment]
Hey guys. I'm sorry for late reply. Yes, installing GtkSourceView fixed it. Thanks.
