### ISSUE TITLE
Cant start gaphor on Ubuntu 22 VM

### ISSUE THREAD

**Issue by DirtyStreetCoder** [gaphor/gaphor#3226]
### Describe the bug
Hi, I was interested in your project and set up a clean new Ubuntu 22.04.4 VM.

### To Reproduce
After installing python 3.10.12 i tried your install documentation

https://docs.gaphor.org/en/latest/linux.html
[Install Flatpak](https://flatpak.org/setup)

Install flatpak-builder

sudo apt-get install flatpak-builder
Install the GNOME SDK

flatpak install flathub org.gnome.Sdk 43
Clone the Flathub repository and install the necessary SDK:

git clone https://github.com/flathub/org.gaphor.Gaphor.git
cd org.gaphor.Gaphor
make setup
Build Gaphor Flatpak

make
Install the Flatpak

make install

When i run 
`gaphor`

I get a bunch of errors

`Settings schema not found and settings won't be saved, run `poe install-schemas`

Traceback (most recent call last):

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/ui/__init__.py", line 67, in app_startup

    application = Application(gtk_app=gtk_app)

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/application.py", line 63, in __init__

    self._services_by_name = initialize("gaphor.appservices", application=self)

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/entrypoint.py", line 13, in initialize

    return init_entry_points(load_entry_points(scope, services), **known_services)

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/entrypoint.py", line 25, in load_entry_points

    cls = ep.load()

  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load

    module = import_module(match.group('module'))

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/ui/help/__init__.py", line 26, in <module>

    class HelpService(Service, ActionProvider):

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/ui/help/__init__.py", line 75, in HelpService

    def _on_use_english_selected(self, switch_row: Adw.SwitchRow, param) -> None:

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__

    raise AttributeError("%r object has no attribute %r" % (

AttributeError: 'gi.repository.Adw' object has no attribute 'SwitchRow'

Traceback (most recent call last):

  File "/home/jr/gaphor_venv/gaphor_venv/lib/python3.10/site-packages/gaphor/ui/__init__.py", line 81, in app_activate

    assert application

AssertionError`

I tried some approaches from you latest video with the same result...
https://www.youtube.com/watch?v=9BYgI1nJCBA

### Expected behavior
gaphor GUI opens

### Screenshots
n.a.

### OS
- [X] Linux (Ubuntu 22.04.4 VM on VirtualBox 7.0.12)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: latest (i assume, don't know how to verify)

### Additional information
A video from scratch would be nice. I may be able to do that once it works.

**Comment by danyeaw** [comment]
Hi @DirtyStreetCoder, Gaphor depends on libadwaita 1.4.0 or newer. If you want to run it in a VM or on any Linux outside of Flatpak, you'll need to have a very new distribution version. For example, Ubuntu 2023.10, openSUSE Tumbleweed, or Fedora 39.

I also checked and this is mentioned in the docs rights under this section: https://docs.gaphor.org/en/latest/linux.html#a-local-environment. It does say latest Ubuntu LTS or newer, in the case you need "or newer" because the next LTS will be released next month. :smile:

**Comment by DirtyStreetCoder** [comment]
Hi @danyeaw , thanks for the quick reply. I did indeed not see that hint :-)

Ok, so i tried it again with ubuntu 23.10.1

Did all the flatpak steps...
.
.
.
cd org.gaphor.Gaphor
make setup
make
make install

but the when i enter "gaphor" I get 
"gaphor: command not found"

Running the make... steps again tells me 
`Error: org.gaphor.Gaphor already installed
error: Failed to install bundle org.gaphor.Gaphor: This version of org.gaphor.Gaphor is already installed
make: *** [Makefile:57: install] Error 1`

What am i doing wrong this time?

Sorry to bother you again.

**Comment by danyeaw** [comment]
Hi @DirtyStreetCoder, it sounds like you are successful building the flatpak which is great. To run a flatpak, you'll need to give the full name like `flatpak run org.gaphor.Gaphor`.
