### ISSUE TITLE
Auto layout throws error

### ISSUE THREAD

**Issue by matgaj** [gaphor/gaphor#3328]
### Describe the bug
Ctrl + Shift + L automatic layout throws an unexpected error. Orthogonal auto layout does still execute but the layout isn't orthogonal.

### To Reproduce
Use the automatic layout function.
Unexpected error occurs and the layout isn't changed.
```

Gaphor version:         2.25.1
Operating System:       Windows (11)
Display:                GdkWin32Display
Python version:         3.12.3
GTK version:            4.14.2
Adwaita version:        1.5.0
GtkSourceView version:  5.12.0
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.48.1
Pycairo version:        1.26.0


Errors:

Time since application startup: 0:00:07
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\actiongroup.pyc", line 145, in _action_activate
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 49, in layout_current_diagram
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 64, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 76, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 172, in apply_layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 358, in parse_edge_pos
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 365, in parse_point
|ValueError: could not convert string to float: '\\\r\n807.5'
└─────────────────────────────╌┄┈
Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\actiongroup.pyc", line 145, in _action_activate
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 49, in layout_current_diagram
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 64, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 76, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 172, in apply_layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 358, in parse_edge_pos
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 365, in parse_point
|ValueError: could not convert string to float: '\\\r\n807.5'
└─────────────────────────────╌┄┈
Time since application startup: 0:02:04
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\actiongroup.pyc", line 145, in _action_activate
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 49, in layout_current_diagram
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 64, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 76, in layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 172, in apply_layout
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 358, in parse_edge_pos
|  File "C:\Program Files\Gaphor\_internal\gaphor\plugins\autolayout\pydot.pyc", line 365, in parse_point
|ValueError: could not convert string to float: '\\\r\n807.5'
└─────────────────────────────╌┄┈

```

### Expected behavior
A layout is suggested normally

### Screenshots
![obraz](https://github.com/gaphor/gaphor/assets/10777373/e8bc2b85-2b0a-4b5e-9683-2cfb83414169)
![obraz](https://github.com/gaphor/gaphor/assets/10777373/8e2a6fc3-9399-4020-b6e5-f5abb0b3f1c2)
![obraz](https://github.com/gaphor/gaphor/assets/10777373/8a5cad53-73e7-4f76-84fe-90af8b05aa97)

### OS
Windows 11 Pro 23H2

### Version
Version of Gaphor: 2.25.1

### Additional information
 Not sure what condition must be met in the diagram itself. It worked initially and stopped working at some point during my work.

**Comment by amolenaar** [comment]
Hi @matgaj, Thanks for your report.

At first glance it looks like there's an issue in how the dot file is created. That file is handed to graphviz to do the actual placement. Can you share the model? That will make debugging a lot easier 😃 .

**Comment by matgaj** [comment]
Github won't accept .gaphor as an extension so i changed it to .txt
[uml.txt](https://github.com/gaphor/gaphor/files/15483011/uml.txt)

**Comment by amolenaar** [comment]
I can't reproduce it on my machine. It renders fine. However, I think it's good to be a bit defensive on what we get back from Graphviz.

<img width="870" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/b3bdacbc-e7be-4215-801a-c231e2f93ec2">

**Comment by danyeaw** [comment]
@all-contributors please add @matgaj for bug

**Comment by danyeaw** [comment]
Thanks @matgaj for the issue report!
