### ISSUE TITLE
Error: "Handle is not an end handle"

### ISSUE THREAD

**Issue by ghillebrand** [gaphor/gaphor#3331]
### Describe the bug

Building a package dependency diagram, linking a node within a node ("A" on the diagram) to a device within another node ("B"), using a dependency. The dependency disappeared, and the target device now shows as pale grey. Every action now pops up the error warning, with a request to log the error.

![image](https://github.com/gaphor/gaphor/assets/9532378/49609f02-dfc0-4c29-bb96-252f361718a4)

### To Reproduce
Tried to reopen the model from the last save and recreate the steps, but it didn't recur :/

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

Gaphor version:         2.25.1
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.12.3
GTK version:            4.14.2
Adwaita version:        1.5.0
GtkSourceView version:  5.12.0
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.48.1
Pycairo version:        1.26.0

Errors:
```
Time since application startup: 0:06:06
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
```
<details>
<summary>More stack traces</summary>
Time since application startup: 0:06:09
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:06:12
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:43
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:45
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:48
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:50
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:50
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:52
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 109, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:53
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:08:56
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:09:02
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 107, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 58, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:09:06
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 109, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:09:06
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 109, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
Time since application startup: 0:09:09
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphas\tool\itemtool.pyc", line 122, in on_drag_end
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 39, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\guide.pyc", line 247, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 59, in stop_move
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\tools\handlemove.pyc", line 52, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphas\handlemove.pyc", line 109, in connect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 76, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connector.pyc", line 105, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 131, in disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphas\connections.pyc", line 148, in _disconnect_item
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\_connector.pyc", line 105, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 329, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 294, in disconnect_connected_items
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\connectors.pyc", line 323, in disconnect
|  File "C:\Program Files\Gaphor\_internal\gaphas\item.pyc", line 378, in opposite
|KeyError: 'Handle is not an end handle'
└─────────────────────────────╌┄┈
</details>

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor:

**Comment by ghillebrand** [comment]
Herewith same.  I was working on the file later, and got the same error.
[ISCT IT Architecture bug.zip](https://github.com/user-attachments/files/15525825/ISCT.IT.Architecture.bug.zip)
Thanks for the response.

**Comment by amolenaar** [comment]
Thanks. I'll dig into it.

**Comment by amolenaar** [comment]
I can see the exception, but only after I close the GUI session.

```
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
  + Exception Group Traceback (most recent call last):
  |   File "/Users/arjan/Development/gaphor/gaphor/ui/filemanager.py", line 475, in response
  |     handler(answer)
  |   File "/Users/arjan/Development/gaphor/gaphor/ui/filemanager.py", line 419, in response
  |     confirm_shutdown()
  |   File "/Users/arjan/Development/gaphor/gaphor/ui/filemanager.py", line 400, in confirm_shutdown
  |     self.event_manager.handle(SessionShutdown())
  |   File "/Users/arjan/Development/gaphor/gaphor/core/eventmanager.py", line 83, in handle
  |     self._events.handle(queue.pop())
  |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 63, in handle
  |     raise ExceptionGroup("Error while handling events", exceptions)
  | ExceptionGroup: Error while handling events (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 59, in handle
    |     handler(event)
    |   File "/Users/arjan/Development/gaphor/gaphor/application.py", line 127, in on_session_shutdown
    |     self.shutdown_session(session)
    |   File "/Users/arjan/Development/gaphor/gaphor/application.py", line 150, in shutdown_session
    |     session.shutdown()
    |   File "/Users/arjan/Development/gaphor/gaphor/application.py", line 229, in shutdown
    |     self.shutdown_service(name, srv)
    |   File "/Users/arjan/Development/gaphor/gaphor/application.py", line 236, in shutdown_service
    |     srv.shutdown()
    |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/elementfactory.py", line 75, in shutdown
    |     self.flush()
    |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/elementfactory.py", line 196, in flush
    |     element.unlink()
    |   File "/Users/arjan/Development/gaphor/gaphor/core/modeling/diagram.py", line 386, in unlink
    |     self.connections.remove_connections_to_item(item)
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/connections.py", line 165, in remove_connections_to_item
    |     disconnect_item(*cinfo)
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/connections.py", line 148, in _disconnect_item
    |     callback(item, handle, connected, port)
    |   File "/Users/arjan/Development/gaphor/gaphor/diagram/_connector.py", line 112, in __call__
    |     adapter.disconnect(handle)
    |   File "/Users/arjan/Development/gaphor/gaphor/diagram/connectors.py", line 329, in disconnect
    |     self.disconnect_connected_items()
    |   File "/Users/arjan/Development/gaphor/gaphor/diagram/connectors.py", line 294, in disconnect_connected_items
    |     adapter.disconnect(cinfo.handle)
    |   File "/Users/arjan/Development/gaphor/gaphor/diagram/connectors.py", line 323, in disconnect
    |     opposite = line.opposite(handle)
    |                ^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gaphas/item.py", line 378, in opposite
    |     raise KeyError("Handle is not an end handle")
    | KeyError: 'Handle is not an end handle'
    +------------------------------------
```
