### ISSUE TITLE
Moving relationships in the model browser trigger

### ISSUE THREAD

**Issue by ghillebrand** [gaphor/gaphor#3359]
### Describe the bug
Moving relationships in the model browser, into or out of the model, generates and error.

### To Reproduce
1. Created a new, generic model
2. Add 2 classes and an association
3. In the model browser, attempt to move the relationships out of the model, onto/ into "New Diagram"
4. Nothing happens in the browser, but the error message pops up.

Image of scenario above:
![image](https://github.com/gaphor/gaphor/assets/9532378/1b47fc78-2c89-495e-9472-fec308c6da1d)

Initially, created in this test/ scratch model, created the same way as above.
Now the relationships are root objects in the model, and cannot be moved into a model.

![image](https://github.com/gaphor/gaphor/assets/9532378/c87c22ce-c949-4d11-8ca2-ad077d2345f8)
[New Model error 2024_06_22.zip](https://github.com/user-attachments/files/15936204/New.Model.error.2024_06_22.zip)

Error Log:
```
Gaphor version:         2.25.1
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.12.3
GTK version:            4.14.2
Adwaita version:        1.5.0
GtkSourceView version:  5.12.0
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.48.1
Pycairo version:        1.26.0


Errors:

Time since application startup: 1:40:27
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 583, in list_item_drop_drop
|AttributeError: 'NoneType' object has no attribute 'owner'
└─────────────────────────────╌┄┈
Time since application startup: 2:07:16
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 590, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 2:21:00
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 590, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 2:25:36
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 590, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 2:25:39
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 590, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 20, in change_owner
|AttributeError: 'NoneType' object has no attribute 'model'
└─────────────────────────────╌┄┈
Time since application startup: 2:28:47
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 590, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 26, in change_owner
|AttributeError: 'NoneType' object has no attribute 'owner'
└─────────────────────────────╌┄┈
```

### Expected behaviour
The relationships are moved to beneath the element on which they are dropped.
If they can't be dropped, ideally, a "no entry" cursor" displays. Alternatively, nothing happens (as per current action), but also no error popup.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows (10)

### Version
Version of Gaphor: 2.25.1

### Additional information
Not a high priority issue, but it does seem to sometimes hinder structuring the model correctly.

**Comment by danyeaw** [comment]
@all-contributors please add @ghillebrand for bug
