### ISSUE TITLE
Add the same picture to further diagrams

### ISSUE THREAD

**Issue by itafraze** [gaphor/gaphor#3427]
### Describe the bug

An error occurrs when attempting to add the same picture to a second diagram

### To Reproduce

Part A:
1. Open a diagram;
2. Add a `Picture` from the `General` palette;
3. Select the newly created picture placeholder in the diagram (crossed white box);
4. On the Property Editor, click `Select picture...` and pick a valid image file;
5. Create/open a new  diagram;
6. Either:
    a. Drag 'n drop the picture (`<None>`)  into the second diagram
    b. Right click the `<None>` and `Add to diagram`
7. Check the error message;

<details>
<summary>Click to expand the Error Report</summary>

```
Gaphor version:         2.26.0
Operating System:       Linux (6.9.12-200.fc40.x86_64)
Display:                GdkWaylandDisplay
Python version:         3.11.9
GTK version:            4.14.4
Adwaita version:        1.5.2
GtkSourceView version:  5.12.1
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.48.2
Pycairo version:        1.26.1


Errors:

Time since application startup: 0:01:00
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphas/decorators.py", line 86, in async_wrapper
|    func(*args, **kwargs)
|    │     │       └ {}
|    │     └ (<gtkview.GtkView object at 0x7f281eb5a840 (GaphasView at 0x562c9498d750)>,)
|    └ <function GtkView.update at 0x7f28348cc5e0>
|  File "/app/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 288, in update
|    self.update_bounding_box(dirty_items)
|    │                        └ {<gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>}
|    └ <gtkview.GtkView object at 0x7f281eb5a840 (GaphasView at 0x562c9498d750)>
|  File "/app/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 325, in update_bounding_box
|    painter.paint_item(item, cr)
|    │                  │     └ <cairo.Context object at 0x7f2828159930>
|    │                  └ <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>
|    └ <gaphor.diagram.painter.ItemPainter object at 0x7f281eb95190>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/painter.py", line 41, in paint_item
|    item.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/presentation.py", line 166, in draw
|    self._shape.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 458, in draw
|    self.icon.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 572, in draw
|    self.child.draw(new_context, bounding_box)
|    │               │            └ Rectangle(0, 0, 200.0, 200.0)
|    │               └ DrawContext(cairo=<cairo.Context object at 0x7f2828159930>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    └ <gaphor.diagram.shapes.CssNode object at 0x7f2834a90c90>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 273, in draw
|    self.draw_vertical(context, bounding_box)
|    │                  │        └ Rectangle(0, 0, 200.0, 200.0)
|    │                  └ DrawContext(cairo=<cairo.Context object at 0x7f2828159930>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    └ <gaphor.diagram.shapes.Box object at 0x7f2834a913d0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 315, in draw_vertical
|    self._draw_border(self, context, bounding_box)
|    │                 │     │        └ Rectangle(0, 0, 200.0, 200.0)
|    │                 │     └ DrawContext(cairo=<cairo.Context object at 0x7f2828159930>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    │                 └ <gaphor.diagram.shapes.Box object at 0x7f2834a913d0>
|    └ <gaphor.diagram.shapes.Box object at 0x7f2834a913d0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/general/picture.py", line 94, in draw_image
|    self.height = min(self.height, context_height)
|    │                 │            └ 149.78902953586498
|    │                 └ <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>
|    └ <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/element.py", line 239, in __setattr__
|    super().__setattr__(key, value)
|                        │    └ 149.78902953586498
|                        └ 'height'
|  File "/app/lib/python3.11/site-packages/gaphas/item.py", line 193, in height
|    h[SE].pos.y = h[SW].pos.y = h[NW].pos.y + height
|    │ │           │ │           │ │           └ 149.78902953586498
|    │ │           │ │           │ └ 0
|    │ │           │ │           └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|    │ │           │ └ 3
|    │ │           └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|    │ └ 2
|    └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 64, in _set_y
|    self._y.value = v
|    │               └ 149.78902953586498
|    └ <Position object on (Variable(200, 40), Variable(200, 40))>
|  File "/app/lib/python3.11/site-packages/gaphas/solver/variable.py", line 111, in set_value
|    self.notify(oldval)
|    │           └ 200.0
|    └ Variable(200, 40)
|  File "/app/lib/python3.11/site-packages/gaphas/solver/variable.py", line 90, in notify
|    handler(self, old)
|    │       │     └ 200.0
|    │       └ Variable(200, 40)
|    └ <bound method Position._propagate_y of <Position object on (Variable(200, 40), Variable(200, 40))>>
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 50, in _propagate_y
|    self.notify((self._x.value, oldval))
|    │            │              └ 200.0
|    │            └ <Position object on (Variable(200, 40), Variable(200, 40))>
|    └ <Position object on (Variable(200, 40), Variable(200, 40))>
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 42, in notify
|    handler(self, oldpos)
|    │       │     └ (200.0, 200.0)
|    │       └ <Position object on (Variable(200, 40), Variable(200, 40))>
|    └ <bound method HandlePositionUpdate._on_handle_position_update of <gaphor.diagram.general.picture.PictureItem element e6123ebf-55...
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/presentation.py", line 89, in _on_handle_position_update
|    self.handle(HandlePositionEvent(self, handle, old))  # type: ignore[attr-defined]
|    │           │                   │     │       └ (200.0, 200.0)
|    │           │                   │     └ <Handle object on (Variable(200, 40), Variable(200, 40))>
|    │           │                   └ <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>
|    │           └ <class 'gaphor.diagram.presentation.HandlePositionEvent'>
|    └ <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/element.py", line 209, in handle
|    model.handle(event)
|    │            └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7f28281ae0d0>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x7f28295f5110>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/elementfactory.py", line 220, in handle
|    self.event_manager.handle(event)
|    │                         └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7f28281ae0d0>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x7f28295f5110>
|  File "/app/lib/python3.11/site-packages/gaphor/core/eventmanager.py", line 77, in handle
|    self._priority.handle(event)
|    │                     └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7f28281ae0d0>
|    └ <gaphor.core.eventmanager.EventManager object at 0x7f2829acb9d0>
|  File "/app/lib/python3.11/site-packages/generic/event.py", line 61, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|          │                                             └ [NotInTransactionException('Updating state outside of a transaction: Reverse event HandlePositionEvent for element <gaphor.diagr...
|          └ <class 'ExceptionGroup'>
|ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/app/lib/python3.11/site-packages/generic/event.py", line 57, in handle
  |    handler(event)
  |    │       └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7f28281ae0d0>
  |    └ <bound method UndoManager.undo_reversible_event of <gaphor.services.undomanager.UndoManager object at 0x7f28281040d0>>
  |  File "/app/lib/python3.11/site-packages/gaphor/services/undomanager.py", line 312, in undo_reversible_event
  |    self.add_undo_action(undo_reversible_event)
  |    │                    └ <function UndoManager.undo_reversible_event.<locals>.undo_reversible_event at 0x7f282813aac0>
  |    └ <gaphor.services.undomanager.UndoManager object at 0x7f28281040d0>
  |  File "/app/lib/python3.11/site-packages/gaphor/services/undomanager.py", line 191, in add_undo_action
  |    raise NotInTransactionException(
  |gaphor.services.undomanager.NotInTransactionException: Updating state outside of a transaction: Reverse event HandlePositionEvent for element <gaphor.diagram.general.picture.PictureItem element e6123ebf-55b5-11ef-8d2c-9d98517baa58>..
  └─────────────────────────────╌┄┈
```

</details>

Part B:

8. Add one or more `Picture` from the `General` palette  into the second diagram;
    - If with drag 'n drop, observe how something is actually there while dragging 
9. The newly added picture may or may not trigger the same error (not systematic);
   - Check the error message

<details>
<summary>Click to expand the further Error Reports</summary>

```
Time since application startup: 0:02:03
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphas/decorators.py", line 86, in async_wrapper
|    func(*args, **kwargs)
|    │     │       └ {}
|    │     └ (<gtkview.GtkView object at 0x7fcc37c9d340 (GaphasView at 0x559200a53f40)>,)
|    └ <function GtkView.update at 0x7fcc4dba45e0>
|  File "/app/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 288, in update
|    self.update_bounding_box(dirty_items)
|    │                        └ {<gaphor.diagram.general.picture.PictureItem element a510a4ac-55b7-11ef-a9f3-43f829a37f2e>, <gaphor.diagram.general.picture.Pict...
|    └ <gtkview.GtkView object at 0x7fcc37c9d340 (GaphasView at 0x559200a53f40)>
|  File "/app/lib/python3.11/site-packages/gaphas/view/gtkview.py", line 325, in update_bounding_box
|    painter.paint_item(item, cr)
|    │                  │     └ <cairo.Context object at 0x7fcc37c69330>
|    │                  └ <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>
|    └ <gaphor.diagram.painter.ItemPainter object at 0x7fcc37c964d0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/painter.py", line 41, in paint_item
|    item.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/presentation.py", line 166, in draw
|    self._shape.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 458, in draw
|    self.icon.draw(
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 572, in draw
|    self.child.draw(new_context, bounding_box)
|    │               │            └ Rectangle(0, 0, 200.0, 200.0)
|    │               └ DrawContext(cairo=<cairo.Context object at 0x7fcc37c69330>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    └ <gaphor.diagram.shapes.CssNode object at 0x7fcc351d2ed0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 273, in draw
|    self.draw_vertical(context, bounding_box)
|    │                  │        └ Rectangle(0, 0, 200.0, 200.0)
|    │                  └ DrawContext(cairo=<cairo.Context object at 0x7fcc37c69330>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    └ <gaphor.diagram.shapes.Box object at 0x7fcc351d2dd0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/shapes.py", line 315, in draw_vertical
|    self._draw_border(self, context, bounding_box)
|    │                 │     │        └ Rectangle(0, 0, 200.0, 200.0)
|    │                 │     └ DrawContext(cairo=<cairo.Context object at 0x7fcc37c69330>, style={'color': (1.0, 1.0, 1.0, 1.0), 'font-family': 'sans', 'font-s...
|    │                 └ <gaphor.diagram.shapes.Box object at 0x7fcc351d2dd0>
|    └ <gaphor.diagram.shapes.Box object at 0x7fcc351d2dd0>
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/general/picture.py", line 94, in draw_image
|    self.height = min(self.height, context_height)
|    │                 │            └ 149.78902953586498
|    │                 └ <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>
|    └ <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/element.py", line 239, in __setattr__
|    super().__setattr__(key, value)
|                        │    └ 149.78902953586498
|                        └ 'height'
|  File "/app/lib/python3.11/site-packages/gaphas/item.py", line 193, in height
|    h[SE].pos.y = h[SW].pos.y = h[NW].pos.y + height
|    │ │           │ │           │ │           └ 149.78902953586498
|    │ │           │ │           │ └ 0
|    │ │           │ │           └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|    │ │           │ └ 3
|    │ │           └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|    │ └ 2
|    └ [<Handle object on (Variable(0, 40), Variable(0, 40))>, <Handle object on (Variable(200, 40), Variable(0, 40))>, <Handle object ...
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 64, in _set_y
|    self._y.value = v
|    │               └ 149.78902953586498
|    └ <Position object on (Variable(200, 40), Variable(149.789, 40))>
|  File "/app/lib/python3.11/site-packages/gaphas/solver/variable.py", line 111, in set_value
|    self.notify(oldval)
|    │           └ 200.0
|    └ Variable(149.789, 40)
|  File "/app/lib/python3.11/site-packages/gaphas/solver/variable.py", line 90, in notify
|    handler(self, old)
|    │       │     └ 200.0
|    │       └ Variable(149.789, 40)
|    └ <bound method Position._propagate_y of <Position object on (Variable(200, 40), Variable(149.789, 40))>>
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 50, in _propagate_y
|    self.notify((self._x.value, oldval))
|    │            │              └ 200.0
|    │            └ <Position object on (Variable(200, 40), Variable(149.789, 40))>
|    └ <Position object on (Variable(200, 40), Variable(149.789, 40))>
|  File "/app/lib/python3.11/site-packages/gaphas/position.py", line 42, in notify
|    handler(self, oldpos)
|    │       │     └ (200.0, 200.0)
|    │       └ <Position object on (Variable(200, 40), Variable(149.789, 40))>
|    └ <bound method HandlePositionUpdate._on_handle_position_update of <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55...
|  File "/app/lib/python3.11/site-packages/gaphor/diagram/presentation.py", line 89, in _on_handle_position_update
|    self.handle(HandlePositionEvent(self, handle, old))  # type: ignore[attr-defined]
|    │           │                   │     │       └ (200.0, 200.0)
|    │           │                   │     └ <Handle object on (Variable(200, 40), Variable(149.789, 40))>
|    │           │                   └ <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>
|    │           └ <class 'gaphor.diagram.presentation.HandlePositionEvent'>
|    └ <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/element.py", line 209, in handle
|    model.handle(event)
|    │            └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7fcc351e4a50>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x7fcc43594490>
|  File "/app/lib/python3.11/site-packages/gaphor/core/modeling/elementfactory.py", line 220, in handle
|    self.event_manager.handle(event)
|    │                         └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7fcc351e4a50>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x7fcc43594490>
|  File "/app/lib/python3.11/site-packages/gaphor/core/eventmanager.py", line 77, in handle
|    self._priority.handle(event)
|    │                     └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7fcc351e4a50>
|    └ <gaphor.core.eventmanager.EventManager object at 0x7fcc4cd3ea50>
|  File "/app/lib/python3.11/site-packages/generic/event.py", line 61, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|          │                                             └ [NotInTransactionException('Updating state outside of a transaction: Reverse event HandlePositionEvent for element <gaphor.diagr...
|          └ <class 'ExceptionGroup'>
|ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/app/lib/python3.11/site-packages/generic/event.py", line 57, in handle
  |    handler(event)
  |    │       └ <gaphor.diagram.presentation.HandlePositionEvent object at 0x7fcc351e4a50>
  |    └ <bound method UndoManager.undo_reversible_event of <gaphor.services.undomanager.UndoManager object at 0x7fcc4fb7de90>>
  |  File "/app/lib/python3.11/site-packages/gaphor/services/undomanager.py", line 312, in undo_reversible_event
  |    self.add_undo_action(undo_reversible_event)
  |    │                    └ <function UndoManager.undo_reversible_event.<locals>.undo_reversible_event at 0x7fcc37de22a0>
  |    └ <gaphor.services.undomanager.UndoManager object at 0x7fcc4fb7de90>
  |  File "/app/lib/python3.11/site-packages/gaphor/services/undomanager.py", line 191, in add_undo_action
  |    raise NotInTransactionException(
  |gaphor.services.undomanager.NotInTransactionException: Updating state outside of a transaction: Reverse event HandlePositionEvent for element <gaphor.diagram.general.picture.PictureItem element a15ee9d0-55b7-11ef-b7c6-43f829a37f2e>..
  └─────────────────────────────╌┄┈
```

</details>

Part C:

11. Continue adding `Picture` until one is correctly placed;
12. Click on this last picture and drag it around the diagram;
13. Observe  how all added pictures appear.

### Expected behavior

Picture added without errors

### Screenshots 

Steps 1 to 4:
![image-1](https://github.com/user-attachments/assets/c7e1e322-329f-4f0b-8118-6f68691bc8aa)

Step 6 to 7:
![image-2](https://github.com/user-attachments/assets/bbb8cf79-c237-4a27-a11b-02a13df53a04)

Step 8:
![image-3](https://github.com/user-attachments/assets/122ec12c-7395-48a2-a87d-8341e6bdf11c)
![image-4](https://github.com/user-attachments/assets/d8e27d27-d27a-4ec7-a98f-07aef621b22b)

Step 13:
![image-5](https://github.com/user-attachments/assets/068baaa7-2573-43f4-8780-3969b90d9cc6)

### OS
- [x] Linux (Fedora 40)
- [ ] macOS (untested)
- [ ] Windows (untested)

### Version
Version of Gaphor: 2.26.0 (Flatpak)

### Additional information

Without step 4 no error occurs.

**Comment by amolenaar** [comment]
This has been implemented. Gaphor supports a `Picture` type (`Image` in the next release).
