### ISSUE TITLE
Gaphor 3.0: adding image causes error

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3683]
### Describe the bug
Adding image to diagram causes error pop up.
### To Reproduce
1. Create new blank model
2. Add image via toolbar icon
4. See error pop up.

Gaphor version:         3.0.0
Operating System:       Darwin (21.6.0, arm64)
Display:                GdkMacosDisplay
Python version:         3.11.10
GTK version:            4.14.4
Adwaita version:        1.5.0
GtkSourceView version:  5.10.0
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.50.0
Pycairo version:        1.27.0

Errors:

```
Time since application startup: 0:00:07
|Traceback (most recent call last):
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/diagram/tools/placement.py", line 40, in on_drag_begin
|    item = create_item(
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/diagram/tools/placement.py", line 61, in create_item
|    item = factory(view.model, parent)
|           │       │           └ None
|           │       └ <diagramview.DiagramView object at 0x12479ff00 (DiagramView at 0x123cd2630)>
|           └ <function new_item_factory.<locals>.item_factory at 0x115a7f9c0>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/diagram/diagramtoolbox.py", line 105, in item_factory
|    subject = element_factory.create(subject_class)
|              │                      └ <class 'gaphor.UML.uml.Image'>
|              └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x1246d24d0>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/elementfactory.py", line 84, in create
|    return self.create_as(type, generate_id())
|           │              │     └ <function generate_id at 0x10470a200>
|           │              └ <class 'gaphor.UML.uml.Image'>
|           └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x1246d24d0>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/elementfactory.py", line 117, in create_as
|    self.handle(ElementCreated(self, element, diagram))
|    │           │              │     │        └ None
|    │           │              │     └ <gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>
|    │           │              └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x1246d24d0>
|    │           └ <class 'gaphor.core.modeling.event.ElementCreated'>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x1246d24d0>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/elementfactory.py", line 222, in handle
|    self.event_manager.handle(event)
|    │                         └ <gaphor.core.modeling.event.ElementCreated object at 0x123d92fd0>
|    └ <gaphor.core.modeling.elementfactory.ElementFactory object at 0x1246d24d0>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/eventmanager.py", line 103, in handle
|    self._priority.handle(event)
|    │                     └ <gaphor.core.modeling.event.ElementCreated object at 0x123d92fd0>
|    └ <gaphor.core.eventmanager.EventManager object at 0x124685610>
|  File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 63, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|                                                        └ [ExceptionGroup('Error while handling events', [TypeError("Format routine for type <class 'gaphor.UML.uml.Image'> not implemente...
|ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 59, in handle
  |    handler(event)
  |    │       └ <gaphor.core.modeling.event.ElementCreated object at 0x123d92fd0>
  |    └ <bound method UndoManager.undo_create_element_event of <gaphor.services.undomanager.UndoManager object at 0x115c19490>>
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/services/undomanager.py", line 332, in undo_create_element_event
  |    self.add_undo_action(undo_create_event)
  |    │                    └ <function UndoManager.undo_create_element_event.<locals>.undo_create_event at 0x12484e700>
  |    └ <gaphor.services.undomanager.UndoManager object at 0x115c19490>
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/services/undomanager.py", line 192, in add_undo_action
  |    self._action_executed()
  |    └ <gaphor.services.undomanager.UndoManager object at 0x115c19490>
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/services/undomanager.py", line 292, in _action_executed
  |    self.event_manager.handle(ActionEnabled("win.edit-undo", self.can_undo()))
  |    │                         │                              └ <gaphor.services.undomanager.UndoManager object at 0x115c19490>
  |    │                         └ <class 'gaphor.event.ActionEnabled'>
  |    └ <gaphor.services.undomanager.UndoManager object at 0x115c19490>
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/eventmanager.py", line 109, in handle
  |    self._events.handle(queue.pop())
  |    │                   └ deque([])
  |    └ <gaphor.core.eventmanager.EventManager object at 0x124685610>
  |  File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 63, in handle
  |    raise ExceptionGroup("Error while handling events", exceptions)
  |                                                        └ [TypeError("Format routine for type <class 'gaphor.UML.uml.Image'> not implemented yet")]
  |ExceptionGroup: Error while handling events (1 sub-exception)
  └─┬──────────────────────────────╌┄┈
    |Traceback (most recent call last):
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 59, in handle
    |    handler(event)
    |    │       └ <gaphor.core.modeling.event.ElementCreated object at 0x123d92fd0>
    |    └ <bound method PreferencesStack._style_sheet_created of <gaphor.ui.elementeditor.PreferencesStack object at 0x115c20310>>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/treemodel.py", line 292, in on_element_created
    |    self.add_element(event.element)
    |    │                └ <gaphor.core.modeling.event.ElementCreated object at 0x123d92fd0>
    |    └ <gaphor.UML.treemodel.TreeModel object at 0x124735750>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/treemodel.py", line 245, in add_element
    |    owner_branch.append(element)
    |    │                   └ <gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>
    |    └ <gaphor.UML.treemodel.Branch object at 0x12476b910>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/treemodel.py", line 91, in append
    |    self.elements.append(TreeItem(element))
    |    │                    │        └ <gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>
    |    │                    └ <class 'gaphor.UML.treemodel.TreeItem'>
    |    └ <gaphor.UML.treemodel.Branch object at 0x12476b910>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/treemodel.py", line 32, in __init__
    |    self.sync()
    |    └ <treemodel.TreeItem object at 0x124811d80 (gaphor+UML+treemodel+TreeItem at 0x600003f822a0)>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/treemodel.py", line 57, in sync
    |    self.readonly_text = format(element) or gettext("<None>")
    |    │                    │      │           └ <bound method NullTranslations.gettext of <gettext.NullTranslations object at 0x1032a7bd0>>
    |    │                    │      └ <gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>
    |    │                    └ <function format at 0x11541c040>
    |    └ <treemodel.TreeItem object at 0x124811d80 (gaphor+UML+treemodel+TreeItem at 0x600003f822a0)>
    |  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 909, in wrapper
    |    return dispatch(args[0].__class__)(*args, **kw)
    |           │        │                   │       └ {}
    |           │        │                   └ (<gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>,)
    |           │        └ (<gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>,)
    |           └ <function singledispatch.<locals>.dispatch at 0x11539d580>
    |  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/format.py", line 15, in format
    |    raise TypeError(f"Format routine for type {type(el)} not implemented yet")
    |                                                    └ <gaphor.UML.uml.Image element e41c85bc-be58-11ef-8a5e-ba28606445a9>
    |TypeError: Format routine for type <class 'gaphor.UML.uml.Image'> not implemented yet
    └─────────────────────────────╌┄┈
  └─────────────────────────────╌┄┈
```

### Expected behavior
Add image should work as expected.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x ] macOS
- [ ] Windows

### Version
Version of Gaphor 3.0:

**Comment by amolenaar** [comment]
@mikekidner Thanks for finding this.
