### ISSUE TITLE
gaphor 3.0: new sysml diagram icons not representable on diagrams

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3698]
### Describe the bug
When dragging a diagram onto another diagram, (e.g when making a model index) the following error is thrown:
"Element can't be represented on the diagram"

### To Reproduce
1. create sysml diagram (with frames)
2. create non-sysml diagram 
4. drag the icon from sysml diagram onto the non-sysml diagram
5. See error
6. drag non-sysml diagram, onto sysml diagram - see no error.

Gaphor version:         3.0.0
Operating System:       Darwin (21.6.0, arm64)
Display:                GdkMacosDisplay
Python version:         3.13.0
GTK version:            4.14.4
Adwaita version:        1.5.0
GtkSourceView version:  5.10.0
Cairo version:          1.18.0
Pango version:          1.52.2
PyGObject version:      3.50.0
Pycairo version:        1.27.0

Errors:

Time since application startup: 0:13:15
|Traceback (most recent call last):
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/toolbox.py", line 233, in _flowbox_drag_prepare
|    if not child.draggable:
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:13:15
|Traceback (most recent call last):
|  File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/toolbox.py", line 233, in _flowbox_drag_prepare
|    if not child.draggable:
|AttributeError: 'NoneType' object has no attribute 'draggable'

### Expected behavior
Diagram icons should be able to be represented on diagrams as in 2.27.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x ] macOS
- [ ] Windows

### Version
Version of Gaphor:3.00

**Comment by danyeaw** [comment]
Thanks @mikekidner for catching this before our release 👍

**Comment by mikekidner** [comment]
@danyeaw / @amolenaar  This still appears to be an issue.... see discussion 3759

**Comment by amolenaar** [comment]
@mikekidner My bad, made those changes but forgot to add them as part of the PR (forgot to push).

It's fixed by #3744, but that still needs to be released.
