### ISSUE TITLE
Gtk version problem?

### ISSUE THREAD

**Issue by rkoyama1623** [gaphor/gaphor#796]
**Describe the bug**
I couldn't run gaphor using poetry, although I followed the following gaphor installation instruction.
https://gaphor.readthedocs.io/en/latest/linux.html

Do you have any idea? 
I'm really excited with this project. Please help me if possible.
Thank you.

**To Reproduce**
```
$ pyenv install 3.9.5
$ sudo apt-get install -y python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
$ pyenv exec pip install poetry
$ git clone https://github.com/gaphor/gaphor.git
$ cd gaphor
$ poetry install
$ poetry run gaphor
(gaphor:24802): Gtk-WARNING **: 02:09:26.339: Theme parsing error: gtk.css:1:0: Expected a valid selector
Traceback (most recent call last):
  File "/home/rkoyama/src/gaphor/gaphor/ui/__init__.py", line 111, in app_activate
    application.new_session()
  File "/home/rkoyama/src/gaphor/gaphor/application.py", line 86, in new_session
    return self._new_session(services=services)
  File "/home/rkoyama/src/gaphor/gaphor/application.py", line 103, in _new_session
    session = Session(services=services)
  File "/home/rkoyama/src/gaphor/gaphor/application.py", line 189, in __init__
    services_by_name: Dict[str, Service] = initialize("gaphor.services", services)
  File "/home/rkoyama/src/gaphor/gaphor/entrypoint.py", line 13, in initialize
    return init_entrypoints(load_entrypoints(scope, services), **known_services)
  File "/home/rkoyama/src/gaphor/gaphor/entrypoint.py", line 20, in load_entrypoints
    cls = ep.load()
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/home/rkoyama/.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rkoyama/src/gaphor/gaphor/ui/diagrams.py", line 11, in <module>
    from gaphor.ui.diagrampage import DiagramPage
  File "/home/rkoyama/src/gaphor/gaphor/ui/diagrampage.py", line 8, in <module>
    from gaphas.segment import LineSegmentPainter
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/gaphas/segment.py", line 13, in <module>
    from gaphas.tool.itemtool import MoveType, item_at_point
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/gaphas/tool/__init__.py", line 36, in <module>
    from gaphas.tool.scroll import scroll_tool
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/gaphas/tool/scroll.py", line 6, in <module>
    def scroll_tool(view: GtkView, speed: int = 5) -> Gtk.EventControllerScroll:
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/home/rkoyama/.pyenv/versions/3.9.5/envs/gaphor/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'EventControllerScroll'
```

**Expected behavior**
By the above commands, I should have gaphor run and open the GUI window.

**OS**
- [x] Linux (Ubuntu 18.04)
- [ ] macOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: origin/master

**Additional context**
I checked the Gtk version, but its version looks the same with the gaphor document above.
```python
>>> import gi
>>> gi.require_version("PangoCairo", "1.0")
>>> gi.require_version("Gtk", "3.0")
>>> gi.require_version("Gdk", "3.0")
>>> import gi.repository.Gtk as Gtk
>>> print(Gtk)
<GtkProxyModule <IntrospectionModule 'Gtk' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Gtk-3.0.typelib'>>
```
```bash
$ dpkg -S /usr/lib/x86_64-linux-gnu/girepository-1.0/Gtk-3.0.typelib 
gir1.2-gtk-3.0:amd64: /usr/lib/x86_64-linux-gnu/girepository-1.0/Gtk-3.0.typelib
```

**Comment by danyeaw** [comment]
Hi @rkoyama1623, thanks for reporting the issue. Gaphor is currently using modern features from GTK and you are getting this error because you have GTK 3.20 instead of 3.24 or later. If you want to set up a development environment, you will need the latest Ubuntu LTS or newer.

You can still use Gaphor by following the Flatpak installation instructions at gaphor.org.

**Comment by rkoyama1623** [comment]
@danyeaw 
Thank  you for your quick reply.
I see. 
I'll prepare other environment to run gaphor on it.
Thank  you very  much.

**Comment by danyeaw** [comment]
@rkoyama1623 Ok great! I also updated the docs to make the Linux environment requirements more clear :+1:

**Comment by rkoyama1623** [comment]
Thank you for your support(https://github.com/gaphor/gaphor/commit/720e0d7f117f0e24ebcf7190b85045fda12dc65e).
That's very helpful.
