### ISSUE TITLE
Edit comment text

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#84]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

```
gaphor.transaction ERROR Transaction terminated due to an exception, performing a rollback
Traceback (most recent call last):
  File "/Users/arjan/Development/gaphor/gaphor/transaction.py", line 27, in _transactional
    r = func(*args, **kwargs)
  File "/Users/arjan/Development/gaphor/gaphor/adapters/propertypages.py", line 503, in _on_body_change
    buffer.get_start_iter(), buffer.get_end_iter()
TypeError: Gtk.TextBuffer.get_text() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/Users/arjan/Development/gaphor/gaphor/transaction.py", line 27, in _transactional
    r = func(*args, **kwargs)
  File "/Users/arjan/Development/gaphor/gaphor/adapters/propertypages.py", line 503, in _on_body_change
    buffer.get_start_iter(), buffer.get_end_iter()
TypeError: Gtk.TextBuffer.get_text() takes exactly 4 arguments (3 given)
```

### Minimal reproduction of the problem with instructions

Create a Class, add a comment to it (comment + comment line). Open the editor (Edit -> Editor) and start typing.

**Comment by amolenaar** [comment]
Fixed by #95
