### ISSUE TITLE
Recursion limit met when opening document

### ISSUE THREAD

**Issue by mrmonkington** [gaphor/gaphor#894]
**Describe the bug**
Gaphor crashes when I open this diagram, which I created using Gaphor 2.5.1 (flatpak) and saved, then closed earlier (with no errors at the time).

[classes.zip](https://github.com/gaphor/gaphor/files/6808802/classes.zip)

Logs/traceback below

**To Reproduce**
1. Open (after unzipping) the attached file `classes.gaphor`

**Expected behavior**
To be able to view and edit the diagram.

**OS**
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

NOTES:
Ubuntu 20.04

**Version**
Version of Gaphor: master (run from dev environment w/ python 3.9.6) and 2.5.1 (flatpak)

**Additional context**

Traceback:

```
$ gaphor ~/Documents/Work/najork/docs/modeling/classes.gaphor 
gaphor.application INFO Initializing service component_registry
gaphor.application INFO Initializing service event_manager
gaphor.application INFO Initializing service properties
gaphor.application INFO Initializing service modeling_language
gaphor.application INFO Initializing service element_dispatcher
gaphor.application INFO Initializing service element_factory
gaphor.application INFO Initializing service export_menu
gaphor.application INFO Initializing service tools_menu
gaphor.application INFO Initializing service main_window
gaphor.application INFO Initializing service consolewindow
gaphor.application INFO Initializing service toolbox
gaphor.application INFO Initializing service diagrams
gaphor.application INFO Initializing service copy
gaphor.application INFO Initializing service diagram_export
gaphor.application INFO Initializing service elementeditor
gaphor.application INFO Initializing service file_manager
gaphor.application INFO Initializing service namespace
gaphor.application INFO Initializing service recent_files
gaphor.application INFO Initializing service undo_manager
gaphor.application INFO Initializing service sanitizer
gaphor.application INFO Initializing service xmi_export
gaphor.storage.storage INFO Loading file classes.gaphor
gaphor.storage.storage INFO Read 180 elements from file
gaphor.storage.storage WARNING file b'/home/mark/Documents/Work/najork/docs/modeling/classes.gaphor' could not be loaded (maximum recursion depth exceeded while calling a Python object)
> /home/mark/Documents/Work/gaphor/gaphor/core/modeling/properties.py(359)_get_one()
-> v: T | None = getattr(obj, self._name, None)
(Pdb) step
Traceback (most recent call last):
  File "/home/mark/Documents/Work/gaphor/gaphor/ui/__init__.py", line 130, in app_open
    application.new_session(filename=file.get_path())
  File "/home/mark/Documents/Work/gaphor/gaphor/application.py", line 95, in new_session
    return self._new_session(filename=filename, services=services)
  File "/home/mark/Documents/Work/gaphor/gaphor/application.py", line 123, in _new_session
    event_manager.handle(session_created)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/eventmanager.py", line 55, in handle
    self._events.handle(e)
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/generic/event.py", line 64, in handle
    handler(event)
  File "/home/mark/Documents/Work/gaphor/gaphor/ui/filemanager.py", line 273, in _on_session_created
    self.load(event.filename)
  File "/home/mark/Documents/Work/gaphor/gaphor/ui/filemanager.py", line 151, in load
    for _ in async_loader():
  File "/home/mark/Documents/Work/gaphor/gaphor/ui/filemanager.py", line 126, in async_loader
    for percentage in storage.load_generator(
  File "/home/mark/Documents/Work/gaphor/gaphor/storage/storage.py", line 285, in load_generator
    for percentage in load_elements_generator(
  File "/home/mark/Documents/Work/gaphor/gaphor/storage/storage.py", line 169, in load_elements_generator
    yield from _load_attributes_and_references(elements, update_status_queue)
  File "/home/mark/Documents/Work/gaphor/gaphor/storage/storage.py", line 236, in _load_attributes_and_references
    elem.element.load(name, ref.element)
  File "/home/mark/Documents/Work/gaphor/gaphor/diagram/presentation.py", line 158, in load
    super().load(name, value)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 83, in load
    self._on_matrix_changed(None, ())
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 127, in _on_matrix_changed
    self.matrix_i2c.set(*(self.matrix * self.parent.matrix_i2c))
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 99, in set
    self.notify(old)
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 53, in notify
    handler(self, old)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 127, in _on_matrix_changed
    self.matrix_i2c.set(*(self.matrix * self.parent.matrix_i2c))
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 99, in set
    self.notify(old)
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 53, in notify
    handler(self, old)
...
<...repeat many times...>
...
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 127, in _on_matrix_changed
    self.matrix_i2c.set(*(self.matrix * self.parent.matrix_i2c))
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 99, in set
    self.notify(old)
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 53, in notify
    handler(self, old)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 127, in _on_matrix_changed
    self.matrix_i2c.set(*(self.matrix * self.parent.matrix_i2c))
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 99, in set
    self.notify(old)
  File "/home/mark/.cache/pypoetry/virtualenvs/gaphor-8FIS44k0-py3.9/lib/python3.9/site-packages/gaphas/matrix.py", line 53, in notify
    handler(self, old)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/presentation.py", line 126, in _on_matrix_changed
    if self.parent:
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/properties.py", line 126, in __get__
    return self._get(obj)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/properties.py", line 354, in _get
    return self._get_one(obj)
  File "/home/mark/Documents/Work/gaphor/gaphor/core/modeling/properties.py", line 359, in _get_one
    v: T | None = getattr(obj, self._name, None)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by amolenaar** [comment]
This is a nasty one! I'll look into it.

Thanks for reporting :smiley: .

**Comment by amolenaar** [comment]
@mrmonkington I checked the error. Somehow `ClassItem.parent` is the same as `ClassItem`.

I fixed it for this model, but I'm really curious how an item can become a child of itself.

[classes-fixed.zip](https://github.com/gaphor/gaphor/files/6811147/classes-fixed.zip)
